### ISSUE TITLE
Spotify Discovery Queue Support

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#10]
Most of the new music I find is through Spotify's Discovery Queue, and it would be awesome if Harmony could play my discovery queue and save songs.

**Comment by vincelwt** [comment]
Nice idea :) Added to Trello board.

**Comment by NickFlamel** [comment]
I found this: [http://stackoverflow.com/questions/31551308/automatically-save-spotifys-discover-weekly-playlists](url)

**Comment by vincelwt** [comment]
Don't worry I added it in a recent commit and it will be available in next release

**Comment by NickFlamel** [comment]
Yeah, I've been building from source for a while now. I just wasn't following my discovery queue, so it wasn't showing up.
