### ISSUE TITLE
Add Support for Youtube

### ISSUE THREAD

**Issue by Joseph65** [vincelwt/harmony#100]
Could you add support for https://youtube.com/
it is more popular than VK and it has more songs.

**Comment by vincelwt** [comment]
Yes, that could be great :)

**Comment by gabrielkoerich** [comment]
As you already use it to search for Spotify songs, would be nice if we could search and like musics from Youtube!

**Comment by vincelwt** [comment]
YouTube plugin is now available with 0.7 :) I'll try to add playlists support in the future
