### ISSUE TITLE
Sorting functionality

### ISSUE THREAD

**Issue by ctnordcl** [vincelwt/harmony#103]
It would be nice (and in my opinion, necessary) to be able to sort playlists by artist, song name, album, etc...

**Comment by markybob** [comment]
yes please. and "discover" on google play music seems to only go off of the one song i bought from google play. the rest were uploaded to google play manually (and they do show up in harmony, just not useful in the discover section.

**Comment by HexadecimalPython** [comment]
This would be a nice (also necessary in my opinion) to have.

**Comment by vincelwt** [comment]
That'll be the next thing I'll be working one.
