### ISSUE TITLE
Unable to CMD+Q when starting from source on Mac OS

### ISSUE THREAD

**Issue by ctnordcl** [vincelwt/harmony#104]
Every other app does this, and it's actually a simple fix. Keyboard shortcuts can be registered on app startup, and "freed" (deregistered really) on app quit.

**Comment by vincelwt** [comment]
That's weird, the app should already quit with Cmd+q :/ 
Can you see the menu option in the menu bar to quit the app when the app is focused ?

**Comment by ctnordcl** [comment]
Update: It looks like I can hit CMD+Q on the actual app itself, just not when I debug it from source by running npm start on the project directory. That launches Harmony via the electron app (not the actual compiled app on getharmony.xyz) and I can't hit cmd+q on that. I still think this should be handled, because I'm not sure why there's a discrepancy.

**Comment by vincelwt** [comment]
@ctnordcl Thanks for reporting, I'll try fixing that when I can get my hands on a Mac.

**Comment by ctnordcl** [comment]
No worries, I'll try and get a PR up for this soon. I have a Mac that I use for work (automated test engineer here) that I can test this on. I'll try and get a PR up for it soon.

**Comment by vincelwt** [comment]
That'd be great, thanks :)

**Comment by ctnordcl** [comment]
Strange, can't seem to reproduce the bug anymore. Maybe it got fixed? Anyways, closing the issue.

**Comment by ctnordcl** [comment]
Update, looks like it allows you Cmd+Q only before youve started playing a song. This goes for both the source and compiled apps. At least, this is the way it works on for me playing Seven Nation Army via Spotify, not sure how it works for other music services. Cmd+Q did not work after the music started playing.

**Comment by ctnordcl** [comment]
Fixed! See my PR about Menu building, it includes a fix for this.
