### ISSUE TITLE
[Suggestion] Consider minimum dimensions for app

### ISSUE THREAD

**Issue by ctnordcl** [vincelwt/harmony#107]
Right now, you can size it down to be unreasonably small. I would recommend having a minimum size so that form is maintained and it doesn't do this:
<img width="159" alt="issue" src="https://cloud.githubusercontent.com/assets/10139247/20247869/9d2d0e5e-a9a5-11e6-9cfe-01d611147474.png">
<img width="270" alt="suggestion" src="https://cloud.githubusercontent.com/assets/10139247/20247870/9d2f5eb6-a9a5-11e6-8b01-6045a1ecc7e8.png">

**Comment by vincelwt** [comment]
I edited it for larger min window height and width. On OSX the title bar is included in the window size (not on Linux and Windows) so it may result in the controls half hidden when resized at the minimum.
