### ISSUE TITLE
Consider platform-specific menu building on app instantiation

### ISSUE THREAD

**Issue by ctnordcl** [vincelwt/harmony#109]
We really should be taking greater care to provide a thorough UI for our app, since by nature it's cross-platform. I propose we do this by making platform specific menus, since not all platforms behave the same way. Will update with PR soon.

**Comment by mojo2012** [comment]
Frameworks like electron provide such functionality out of the box. It then renders a platform-specific menu: http://electron.atom.io/docs/api/menu/

**Comment by vincelwt** [comment]
I'm closing this, since I think menus are currently as it should be :)
