### ISSUE TITLE
Windows 10 Toasters

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#11]
![screenshot_1](https://cloud.githubusercontent.com/assets/20823203/18318584/3d25b5ae-74f0-11e6-88e0-ba4c59e7e265.jpg)
This notification pops up when a new song plays. I assume it's a placeholder of sorts?

**Comment by vincelwt** [comment]
Mmm, that's supposed to give info about the song name and artist.

WIll look into it, thanks for reporting

**Comment by NickFlamel** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/20823203/18396133/04f58b90-7690-11e6-8f3f-bb56e258cbad.jpg)
This is what the notification looks like in v0.2.3

**Comment by vincelwt** [comment]
Could you try with latest git version ? Harmony [now uses](#57) Electron API for notifications, so it should work

**Comment by NickFlamel** [comment]
Okay, the toasts worked, but I disabled them because they were annoying me a bit. I've re-enabled them, but now they aren't showing.

**Comment by vincelwt** [comment]
Yes, that's because they're supposed to popup only when a track changes, with the app in the background. 
It would be too annoying to have a notification every time we manually play a new track from the app

**Comment by vincelwt** [comment]
Closing as it's solved
