### ISSUE TITLE
Add option to export error logs

### ISSUE THREAD

**Issue by Etheryte** [vincelwt/harmony#111]
I just tried the app for the first time and it looks very promising. However upon trying to load my music from Spotify, I only get a very non-descriptive message: `Error`.  

It would be beneficial for both local debugging, for development purposes and bug reporting to be able to export and inspect error logs from the application.

**Comment by vincelwt** [comment]
You can open the developer tools with ctrl/cmd+alt+i and see the log in the console tab

**Comment by Etheryte** [comment]
Oh, that's super helpful. I think it would be a good idea to add that information either under the development topic in the readme or add it into the issue template (see [this blogpost](https://github.com/blog/2111-issue-and-pull-request-templates)) for a guide.

**Comment by vincelwt** [comment]
Thats a good idea :) I'll do it when I have some time
