### ISSUE TITLE
[OS X] [Bug] Cannot close or hide window with shortcuts

### ISSUE THREAD

**Issue by maxkrieger** [vincelwt/harmony#112]
I can't run <kbd>CMD</kbd>+<kbd>W</kbd> or <kbd>CMD</kbd>+<kbd>H</kbd> to hide the window on OS X.

**Comment by vincelwt** [comment]
Thanks for reporting, I wasn't aware of those shortcuts. I'll take a look at it when I can get my hands on a Mac.

**Comment by vincelwt** [comment]
Should be ok with next release
