### ISSUE TITLE
Integration with Yandex Music

### ISSUE THREAD

**Issue by sojusnik** [vincelwt/harmony#114]
Is it possible to integrate [Yandex Music](https://music.yandex.ru/)?

**Comment by vincelwt** [comment]
If a developer wants to try and implement it, I'll provide help, but for now my focus is on making the app as usable and stable as possible.

**Comment by pasteley** [comment]
When the time will come, u could try [this unofficial api](https://github.com/itsmepetrov/yandex-music-api) and maybe [this article](https://habrahabr.ru/post/133578/) would be helpful (warning: its on russian).

Will w8 for this feature! Thank you!
