### ISSUE TITLE
minimize/close to tray

### ISSUE THREAD

**Issue by markybob** [vincelwt/harmony#115]
there needs to be a minimize/close to tray option. there's no need to waste real estate on background music. thanks.

**Comment by markybob** [comment]
there is "hide player" in tray menu option...but then i dont see any way to restore it. this is on xfce on debian 9. right-licking or left-clicking on the tray icon after "hide player" does nothing.

**Comment by vincelwt** [comment]
Hi,
Did you try using the "Show player" button in the tray after hiding it ?

**Comment by psukys** [comment]
Doesn't the left click show/hide the player anyway?

**Comment by vincelwt** [comment]
On Linux, when you click on the tray icon it hides/show the window. On Win and OSX, right click then click hide player to hide it. In the future maybe the app will be hidden to tray (if it's enabled) when we close the window. Closing this issue as there is already a way to hide it and restore it.
