### ISSUE TITLE
Spotify login popup broken / empty

### ISSUE THREAD

**Issue by QuentinLB** [vincelwt/harmony#116]
Hi !

First, good job building this app it's really well built, thanks !

My issue is with the Spotify login popup, it's completely blank.
![image](https://cloud.githubusercontent.com/assets/6490070/20747009/b0833ed8-b6e8-11e6-8477-85ebb3eac25b.png)
I don't see any errors in console or network logs. 

When I try to close the popup I get this error message : 

![image](https://cloud.githubusercontent.com/assets/6490070/20747113/284d5796-b6e9-11e6-9a35-aacd33cfe7f4.png)

Maybe someone can help ?

**Comment by quentinsikana** [comment]
Hello,
I have the same issue here - blank popup - but without the JavaScript error.
I run Harmony player on MacOS.

**Comment by vincelwt** [comment]
Hi
I'm able to reproduce it, so it must be a change on Spotify's side. I'm working on a fix!

**Comment by quentinsikana** [comment]
Thank you !
I just discovered Harmony and it looks pretty neat, I can't wait for this to be fixed.
Keep up the good work man !

**Comment by QuentinLB** [comment]
Thank you !

**Comment by vincelwt** [comment]
Okay, the problem [came from Electron](https://github.com/electron/electron/issues/7221), and should be fixed now. I have a thing or two to fix before publishing the next release, I'll try to do it soon.
Thank you guys for reporting!

**Comment by vincelwt** [comment]
@QuentinLB @quentinsikana could you try with 0.4.3 ?

**Comment by quentinsikana** [comment]
It works! 🍾

**Comment by QuentinLB** [comment]
Works like a charm 👍
