### ISSUE TITLE
Plugin support for music subreddits?

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#119]
Various subreddits such as /r/listentothis and /r/music are great ways to find new music. Expanding harmony support to allow subreddit additions could also boost the number of people using harmony, as no other music player that I know of allows streaming via a subreddit.

**Comment by vincelwt** [comment]
Interesting idea! Although for now I really have few time to work on the project :/, and priorities are on fixing bugs, and implementing important features.
But definitely a good idea for the future of Harmony!

**Comment by vincelwt** [comment]
Happy to say v0.7 will include a Reddit plugin to add any subreddits :)

**Comment by vincelwt** [comment]
Reddit plugin now available with 0.7 :)
