### ISSUE TITLE
Google 2FactorAuth

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#12]
I can't log in to Google Music because I have 2 factor authentication on my google account.

**Comment by vincelwt** [comment]
Same problem as #8 

An alternative (altough insecure and at your own decision) maybe to enable the insecure app access in your Google account:
https://myaccount.google.com/security?pli=1#connectedapps

Maybe it would allow it to work with 2 factor authentification

**Comment by NickFlamel** [comment]
Thanks, that worked.
