### ISSUE TITLE
Only 25 tracks shown in Loved tracks from Deezer

### ISSUE THREAD

**Issue by greenrd** [vincelwt/harmony#120]
I just installed Harmony 0.4 and logged into Deezer and Soundcloud. Only the first 25 of my loved tracks from Deezer appear in Harmony.

Maybe a bug related to pagination handling in the Deezer API?

**Comment by vincelwt** [comment]
Hi,
I haven't extensively tested the Deezer plugin, so it must be a bug related to pagination indeed.
I'll take a look into it.

**Comment by vincelwt** [comment]
Ok it should be working now. You'll be able to try with next release.
