### ISSUE TITLE
Spotify login blank

### ISSUE THREAD

**Issue by ajtb** [vincelwt/harmony#121]
If I choose the Spotify button, I get a blank window.

![zrzut ekranu 2016-12-21 o 23 54 10](https://cloud.githubusercontent.com/assets/1454989/21409154/f0926746-c7d8-11e6-83cf-dfc2ae5222a0.png)

**Comment by vincelwt** [comment]
Hi,
Are you using the latest version ? It should've been fixed with [0.4.3](https://github.com/vincelwt/harmony/releases/tag/v0.4.3)
