### ISSUE TITLE
Little bug when installing .deb package (folder name)

### ISSUE THREAD

**Issue by jctrebalag** [vincelwt/harmony#122]
Hi,

I've just installed the harmony-0.4.3-amd64.deb and notice that in /usr/local/bin the symlink points to **/opt/harmony/harmony**. However the package created an **/opt/Harmony folder**. Had to manually change the folder name in /opt.

System: Debian 8 Jessie - amd64

Thanks,
Jean-Christophe

**Comment by vincelwt** [comment]
Should be fixed in next release (0.5.1) the package name will now be harmony and not Harmony on Linux.

**Comment by jctrebalag** [comment]
Thank you ! Great app by the way !

**Comment by vincelwt** [comment]
Actually I just checked and even if the package name is set to "harmony" it still creates a /opt/Harmony folder. I can't really control this as electron-builder is making the packages. However the symlink /usr/local/bin seems to correctly point to the executable.
