### ISSUE TITLE
hardcoded icons on tray menu

### ISSUE THREAD

**Issue by varlesh** [vincelwt/harmony#124]
Maybe better use system icons on linux for tray menu?
For example:
```
heart.png - emblem-favorite
hide.png - go-down
next.png - media-skip-forward
pause.png - media-playback-pause
previous.png - media-skip-backward
quit.png - exit
show.png - go-up
```
But hardcoded icons used as fallback...

**Comment by vincelwt** [comment]
Good idea! I'll check how can it be done.

**Comment by vincelwt** [comment]
It didn't seemed possible given the current implementation of the Tray with Electron so I decided to remove all icons to give a more stream-lined experience across all OSs.
