### ISSUE TITLE
Add AudioEq

### ISSUE THREAD

**Issue by varlesh** [vincelwt/harmony#125]
Please add equalizer settings on player.
Example code:
https://github.com/akabekobeko/examples-electron/blob/master/audio-player/src/js/renderer/effect-geq/store/EffectGraphicEqualizerStore.js

**Comment by vincelwt** [comment]
After reflexion I don't think this is something that should be directly integrated within Harmony. There are system-wide equalizers available and this would be difficult to integrate. May be in the future as a third-party plugin ?
