### ISSUE TITLE
Last.fm scrobbling integration does not work

### ISSUE THREAD

**Issue by psukys** [vincelwt/harmony#126]
Sorry for abstract title, but I am unsure on which step does it fail. 
The environment:
> Fedora 25 with "harmony-0.4.4.rpm" installed from [releases page](https://github.com/vincelwt/harmony/releases)

The problem:
After authenticating with Last.fm and playing several songs from various sources (Soundcloud - [Where Are Ü Now (with Justin Bieber) by Jack Ü](https://soundcloud.com/jacku/skrillex-and-diplo-present-1) - and Google Play - [Oceans by Coldplay](https://play.google.com/music/preview/Bu4ruysubpv6lfomxgpcwk3n3we)), no information about scrobbled tracks appears in Last.fm profile.

Suspected problem:
The authentication step exits prematurely: 

 - the text in settings does not change (stays "Scrobble with Last.fm"). 
 - After clicking on the "Scrobble with Last.fm", it opens a window for connecting the Harmony application: ![Connect application window](http://i.imgur.com/9Wpdbe7.png)

**Comment by vincelwt** [comment]
Hi, thanks for reporting. 
I can confirm the bug, I'm working on a fix right now.

**Comment by vincelwt** [comment]
Should be working now, will be availaible with next version.

**Comment by psukys** [comment]
#
