### ISSUE TITLE
Stream for deezer is from youtube?

### ISSUE THREAD

**Issue by AbsoluteZero273** [vincelwt/harmony#128]
As I looked into the code base, I found stream is being gotten from youtube in Deezer integration (searching with artist + song name and even using duration to get the best result). Is this true or did I misunderstand the code?

**Comment by AbsoluteZero273** [comment]
This is not really an issue. Just asking if we could improve upon this?

**Comment by vincelwt** [comment]
Hi,
Yes, as Spotify and Deezer don't allow direct streaming of their tracks, Harmony fetch their tracks on YouTube. This isn't a perfect solution but it is the only one that I see as of now :/

**Comment by AbsoluteZero273** [comment]
I don't know about spotify but Deezer does provide JS SDK for the player. But the downside is it requires flash and the player integration might be different from what we are doing.

**Comment by vincelwt** [comment]
Yes, I meant like Soundcloud, a way to fetch the audio directly.
