### ISSUE TITLE
Where is cache stored?

### ISSUE THREAD

**Issue by lucianosb** [vincelwt/harmony#131]
I'm running harmony in a SSD and would like to move the songs it caches to another hard disk. 

I'm probably being over cautious with the number of writes I perform on my SSD but since I only work listening to music, I might give a try to redirect writes to another HD (probably with a symlink).

**Comment by vincelwt** [comment]
Hi,

Harmony doesn't cache the songs, but only their metadatas, so it can load the track list faster.

On Linux, Harmony stores the data to _~/.config/configstore/harmony.json_

**Comment by lucianosb** [comment]
Thanks! That sure is helpful since Deezer doesn't have an app for Linux, Harmony looks like the best approach so far.

**Comment by pra85** [comment]
@vincelwt I had a question. Would it be possible to store the songs in cache or not (likely due to some restrictions put in place in the Terms & Conditions of the services whose APIs Harmony consumes)?

**Comment by vincelwt** [comment]
@pra85 Yes, I think it would violate most the APIs terms we are using.
