### ISSUE TITLE
Spotify not functioning

### ISSUE THREAD

**Issue by moikeha** [vincelwt/harmony#139]
I do have a premium account, logged in properly, nothing actually plays under Spotify though it has all my playlists and songs. Play music functions properly.

I'm on Elementary OS, a linux distro based on Ubuntu 16.04 LTS.

How can I get you the proper logs in what is happening?

**Comment by vincelwt** [comment]
Hi,
You can access the logs by pressing ctrl+alt+i and opening the "console" tab. 
That would be really useful!

**Comment by moikeha** [comment]
> We are on a -linux- system
Mediakeys module not found.
changed Object
changed Object
changed Object
Testing internet...
listView
Latest release is v0.4.4 and we're running undefined
listView
Everything over
listView
listView
changed Object {Metadata: Object}
changed Object {PlaybackStatus: "Playing"}
Uncaught TypeError: Cannot read property 'formats' of undefined
Uncaught TypeError: Cannot read property 'formats' of undefined

Expanding the errors:

> api.js:382 Uncaught TypeError: Cannot read property 'formats' of undefined
(anonymous function) @ api.js:382
(anonymous function) @ info.js:160
(anonymous function) @ sig.js:31
emitOne @ events.js:96
emit @ events.js:188
socketCloseListener @ _http_client.js:284
emitOne @ events.js:101
emit @ events.js:188_
emitErrorNT @ net.js:1272
_combinedTickCallback	@ internal/process/next_tick.js:74
_tickCallback @ internal/process/next_tick.js:98

**Comment by alejuu** [comment]
Hi I'm having the same problem 
Logs:
`
We are on a -linux- system
Mediakeys module not found.
changed Object
changed Object
changed Object
Testing internet...
Latest release is v0.4.4 and we're running undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'discover' of undefined
coverFlowView
Updating covers
coverFlowView
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Uncaught TypeError: Cannot read property 'items' of undefined
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
changed Object
changed Object
Uncaught (in promise) DOMException: The element has no supported sources.
Error: socket hang up(…)
Uncaught TypeError: Cannot read property 'formats' of undefined
changed Object
changed Object
Uncaught TypeError: Cannot read property 'formats' of undefined
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
Testing internet...
Latest release is v0.4.4 and we're running undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
TypeError: Cannot read property 'url' of undefined(…)
TypeError: Cannot read property 'url' of undefined(…)
Uncaught TypeError: Cannot read property 'items' of undefined
coverFlowView
Updating covers
coverFlowView
Testing internet...
Error: socket hang up(…)
Latest release is v0.4.4 and we're running undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Uncaught TypeError: Cannot read property 'playlists' of undefined
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
Uncaught TypeError: Cannot read property 'items' of undefined
coverFlowView
Updating covers
coverFlowView
Updating covers
coverFlowView
TypeError: Cannot read property 'url' of undefined(…)
TypeError: Cannot read property 'url' of undefined(…)
coverFlowView
Updating covers
coverFlowView

`

**Comment by mike168m** [comment]
I got it working when I opened the settings dialog and closed which triggered a reload.

**Comment by vincelwt** [comment]
Weird issues, I'll try to reproduce it!

**Comment by vincelwt** [comment]
I'm able to reproduce it and trying to fix it.
