### ISSUE TITLE
flatpak support

### ISSUE THREAD

**Issue by sramkrishna** [vincelwt/harmony#140]
Hey there!  I was wondering if you could perhaps package a flatpak version instead of just a deb?  (I suppose you could use snaps as well since maybe you're using Ubuntu?)  In any case, I can probably get someone to help.

http://flatpak.org/

Thanks!
sri

**Comment by vincelwt** [comment]
Hi!
There is already an .AppImage package available, which allows to use the app on Linux without installing the app.
Furthemore, electron-builder doesn't seems to support atm Flatpak.

**Comment by sramkrishna** [comment]
Thanks for your response.  I'll look into the electron-builder/flatpak and see if I can help out there.

**Comment by vincelwt** [comment]
I'm closing this until support by electron-builder.
