### ISSUE TITLE
Bandcamp Support

### ISSUE THREAD

**Issue by livejamie** [vincelwt/harmony#141]
There isn't really a good desktop player for Bandcamp. Would love to see support.

Tons of great music on there.

**Comment by vincelwt** [comment]
Hi,
Unfornunately, it seems that Bandcamp do not have an API for regular users. Stating their website:
> Labels and merchandise fulfillment partners can interact with their accounts via the Bandcamp API

And I didn't found any other unofficial API wrappers for regular users.
So I don't think this is currently possible :/

**Comment by vincelwt** [comment]
Closing as currently doesn't seems possible
