### ISSUE TITLE
Harmony don't play music of Spotify and Google Play Music

### ISSUE THREAD

**Issue by mmsdivino** [vincelwt/harmony#142]
Hello!
I have installed Harmony v0.4.4 on Ubuntu 16.04 and added my Spotify and Google Play Music accounts.
But, when I played a music (whether Spotify or GPM), Harmony don't play the music.
First I tried to play a music of GMP and, after, of Spotify:

> /opt/Harmony/harmony  --enable-logging
> [27515:0208/142115:INFO:CONSOLE(26)] "We are on a -linux- system", source: file:///opt/Harmony/resources/app/app/js/app.js (26)
> [27515:0208/142115:INFO:CONSOLE(21)] "Mediakeys module not found.", source: file:///opt/Harmony/resources/app/app/js/player.js (21)
> [27515:0208/142115:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142115:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142115:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142115:INFO:CONSOLE(420)] "listView", source: file:///opt/Harmony/resources/app/app/js/main.js (420)
> Failed to encode dictionary
> Failed to encode reply value
> Failed to encode dictionary
> Failed to encode reply value
> [27515:0208/142117:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142117:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142120:INFO:CONSOLE(382)] "Uncaught TypeError: Cannot read property 'formats' of undefined", source: /opt/Harmony/resources/app/app/js/api.js (382)
> [27515:0208/142123:INFO:CONSOLE(420)] "listView", source: file:///opt/Harmony/resources/app/app/js/main.js (420)
> [27515:0208/142126:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142126:INFO:CONSOLE(81)] "changed", source: /opt/Harmony/resources/app/node_modules/mpris-service/index.js (81)
> [27515:0208/142128:INFO:CONSOLE(382)] "Uncaught TypeError: Cannot read property 'formats' of undefined", source: /opt/Harmony/resources/app/app/js/api.js (382)

**Comment by vincelwt** [comment]
Hi!
This bug should be fixed since yesterday. 
So it should be working again with 0.4.5 (on my way to publish it)!

**Comment by mmsdivino** [comment]
Yes! Play everything all right. Thanks for support :)

**Comment by vincelwt** [comment]
Great.
