### ISSUE TITLE
Be clear about licence

### ISSUE THREAD

**Issue by opi** [vincelwt/harmony#143]
Is harmony an open-source / libre software ?

**Comment by vincelwt** [comment]
Hi,
As specified in the package.json file, Harmony is currently under the GPL V3 license, but it may change in future.

**Comment by opi** [comment]
- change for a closed source licence ?
- Adding this info to a LICENCE file and the website could be helpfull. Do you wan't me to do some pull requests ?

**Comment by vincelwt** [comment]
No, change for a more "attribution" axed license (MIT? Apache?), but I still haven't took an in depth look to the licenses available.
I was thinking to add it at the bottom of the README instead of a file, what do you think?

**Comment by opi** [comment]
oh great to see that you will stay open-source !

GitHub can help you choosing a license : https://choosealicense.com/

And, it's more a personnal taste, but having a raw "LICENSE" file aside to the README is a shared habit, and it makes it straight forward to anyone looking at your repository.
Saying that, you do what you want ( as long as the license is pushed forward :p ) 

thanks

**Comment by vincelwt** [comment]
Thank you for the link, very useful and simple!

I added a LICENSE file, containing the GNU GPL-3.0 license. I think it's the best suited license for now.
Thanks!
