### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by mike168m** [vincelwt/harmony#144]
Can we have the player automatically update itself?
Thanks.

**Comment by vincelwt** [comment]
Electron support for auto update is only working on OSX and Windows, and I'm running Linux (hard to develop things for an OS without it). Also, Squirrel requires a server to push the updates, and that is not an option for me atm (server cost and maintaining).

So I'd say for now it's a no (except if someone is willing to try) but that's definitely something I'll keep looking at, or maybe try to make my own auto-update system.

**Comment by vincelwt** [comment]
Closing as probably won't be integrated for now
