### ISSUE TITLE
No sound menu integration in Unity 7.4

### ISSUE THREAD

**Issue by Feichtmeier** [vincelwt/harmony#149]
Ubuntu 16.04.2 Unity 7.4 and I have no soundmenu integration. There is the harmony tray ofc but not in the sound menu indicator.

![image](https://cloud.githubusercontent.com/assets/15329494/23238217/39d91922-f961-11e6-953f-d8e27faa687b.png)

**Comment by vincelwt** [comment]
Hey,
Did you install using the .deb file or are you using the .AppImage ?

**Comment by Feichtmeier** [comment]
I installed it with the .deb

**Comment by vincelwt** [comment]
You could try with 0.5.0 ? It should've been fixed.

**Comment by Feichtmeier** [comment]
![bildschirmfoto vom 2017-03-19 12-02-20](https://cloud.githubusercontent.com/assets/15329494/24080286/20fcf10a-0c9c-11e7-94f4-bc3660ac6456.png)

Sadly not :(
Did a fresh install 2 from your download page

**Comment by vincelwt** [comment]
@Feichtmeier Thanks, I'm working on a fix.

**Comment by vincelwt** [comment]
Ok I'm pretty sure this is fixed now :) will be available with 0.5.1

**Comment by vincelwt** [comment]
0.5.1 release, could you try and confirm ?
