### ISSUE TITLE
Soundcloud/Spotify integrations not working

### ISSUE THREAD

**Issue by isaacvandor** [vincelwt/harmony#151]
### OS: Win10

Souncloud and Spotify integrations are not working (i.e. When I click on the login links to connect those services, nothing happens)

**Comment by poacher2k** [comment]
### OS: Linux Mint 18.1 Cinnamon 64-bit

Same here - nothing happens.

**Comment by thekelvinliu** [comment]
**OS: macOS Sierra 10.12.3**

same here. i just clicked through all the options, and the only ones that seem to work are play music and hype machine.

**Comment by vincelwt** [comment]
Working on it right now

**Comment by vincelwt** [comment]
Ok fixed, small bug for lack of testing (mea culpa), I'll try to publish the new version soon

**Comment by thekelvinliu** [comment]
@poacher2k @isaacvandor is the update working for you both? i just installed v0.4.7 and getting the same issues. going to try to run locally and see if anything's different.

**Comment by poacher2k** [comment]
Works for me!

Den 9. mars 2017 13:37:31 CET, skrev kelvin liu <notifications@github.com>:
>@poacher2k @isaacvandor is the update working for you both? i just
>installed v0.4.7 and getting the same issues. going to try to run
>locally and see if anything's different.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/vincelwt/harmony/issues/151#issuecomment-285340214

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by isaacvandor** [comment]
Can confirm, also works for me.

**Comment by thekelvinliu** [comment]
so i can get the integrations work work only when i run locally. the release still isn't working for me. @vincelwt any ideas why? lmk if there's anything info i should provide/what i can do to help you debug

**Comment by vincelwt** [comment]
@thekelvinliu What do you mean by running locally ? From the sources ? It's weird as the sources should be on the same level as the 0.4.7 release.

**Comment by thekelvinliu** [comment]
yep from the sources. not super familiar with electron apps on mac -- are there any logs i can check to see what's going on?

**Comment by unixfox** [comment]
I can connect but nothing is synchronized with Soundcloud for the feed:
![harmony_130](https://cloud.githubusercontent.com/assets/4016501/23823459/7875ce14-0663-11e7-9676-05bef766ebc2.png)
But it's synchronized for the liked tracks:
![harmony_132](https://cloud.githubusercontent.com/assets/4016501/23823477/d5415ad2-0663-11e7-8227-aa497b658519.png)

**Comment by vincelwt** [comment]
@thekelvinliu Well you can open the log with crl+alt+i, console tab but it won't show what's happening in the settings window. You would have to open the devtools in the settings but for that need to modify the source code.

You could try doing a full reset, uninstall 0.4.7, remove the cached data `~/.config/configstore/harmony.json` and reinstall the latest release.

**Comment by vincelwt** [comment]
@unixfox Seems like an related issue, open another issue with the log (ctrl+alt+i, console tab)

**Comment by vincelwt** [comment]
Should now work with 0.5 :)
