### ISSUE TITLE
Media keys not working in 0.4.7

### ISSUE THREAD

**Issue by poacher2k** [vincelwt/harmony#154]
### OS: Linux Mint 18.1 Cinnamon 64-bit
![screenshot from 2017-03-07 10-22-02](https://cloud.githubusercontent.com/assets/2255960/23650096/3e49ea6c-0321-11e7-8c97-36f7202558b9.png)

Just re-installed 0.4.5 and media keys does indeed work there.

**Comment by vincelwt** [comment]
This must have something to do with MPRIS not working.
I guess on your system the media keys are binded to the system audio menu, and not directly the app (as Harmony doesn't directly supports mediakeys on Linux) 
I'll check what's wrong

**Comment by vincelwt** [comment]
Are you using Harmony from the .AppImage or .deb?

**Comment by poacher2k** [comment]
From the .deb in both cases.

**Comment by vincelwt** [comment]
I'm not 100% sure but I think I found the bug (problem during rebuild). I'll try to correct it with the future releases

**Comment by vincelwt** [comment]
You could try with 0.5.0 ? It should've been fixed.

**Comment by vincelwt** [comment]
Fixed, will be good with 0.5.1

**Comment by vincelwt** [comment]
0.5.1 is out, can you confirm it is working?
