### ISSUE TITLE
Can't add Local Track on Ubuntu 16.04

### ISSUE THREAD

**Issue by alexisduque** [vincelwt/harmony#155]
Clicking on "Listen with local tracks" button in the Settings pane as no effects. Thus I can't add local tracks to Harmony. 

OS: Ubuntu 16.04 
Versions: 0.4.7, 0.4.6 (both from .deb and tar.gz)

**Comment by MonoCow** [comment]
I'm having the same problem, built from source.
Errors with build, but they're just errors with an optional mediakeys dependency: https://cummies.pro/v/KTrn1p49jf/rCE2wXXkLMFEZrYihF7GuIKVqclPpgkZ
No output appears when pressing the local tracks button.

Xubuntu 16.04, Harmony version 0.4.7

**Comment by vincelwt** [comment]
Can confirm, working on it now.
@MonoCow To debug it you would have to enable the dev tools in the settings windows, errors happening in the settings aren't showing in the main dev tools.

**Comment by vincelwt** [comment]
Ok fixed, will be available with next release, in a week or so.

**Comment by alexisduque** [comment]
@vincelwt good job, thanks ! 

Can you mention the commit commit fixing this issue, so we can patch until the next version released ?

**Comment by vincelwt** [comment]
Here it is :)

**Comment by vincelwt** [comment]
Should now work with 0.5 :)
