### ISSUE TITLE
Harmony can't synchronize the feed of Soundcloud

### ISSUE THREAD

**Issue by unixfox** [vincelwt/harmony#156]
Harmony is unable to synchronize the feed of Soundcloud but it can for the liked tracks (maybe it really can't but it fetch the liked tracks from the cache).

## Logs
```
We are on a -linux- system
player.js:237 Mediakeys module not found.
player.js:288 Error loading MPRIS module
(anonymous) @ player.js:288
player.js:289 Error: The module '/opt/Harmony/resources/app/node_modules/dbus/build/Release/dbus.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/Harmony/resources/app/node_modules/dbus/lib/dbus.js:3:13)
    at Object.<anonymous> (/opt/Harmony/resources/app/node_modules/dbus/lib/dbus.js:148:3)
(anonymous) @ player.js:289
utils.js:7 Testing internet...
main.js:431 listView
main.js:276 Latest release is v0.4.7 and we're running undefined
main.js:240 Everything over
main.js:431 listView
2main.js:431 listView
utils.js:7 Testing internet...
main.js:276 Latest release is v0.4.7 and we're running undefined
main.js:240 Everything over
main.js:431 listView
```
![harmony_134](https://cloud.githubusercontent.com/assets/4016501/23823689/31369b82-0668-11e7-8ba1-9fce426c5e6b.png)

## Information about the OS
- OS : ArchLinux
- NodeJS version: v7.7.2
- Installed from: https://aur.archlinux.org/packages/harmony-player (I'm not using the 0.4.6 version but the latest (0.4.7), I installed the package manually using a modified version of the [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD))

**Comment by vincelwt** [comment]
Could you show the log when the library is refreshing ? (Small refresh button bottom left corner). 
The error with the MPRIS module is unrelated to that.

**Comment by unixfox** [comment]
![harmony_137](https://cloud.githubusercontent.com/assets/4016501/23823736/39a12124-0669-11e7-9b8b-c71c098346d8.png)

**Comment by vincelwt** [comment]
@unixfox That is indeed weird, no errors are appearing. Just to be sure, are you following users on SoundCloud ? The feed is created from users you follow which posted/reposted tracks. So maybe you don't have a feed to show?

**Comment by unixfox** [comment]
It was working perfectly until today (I was listening yesterday music on Soundcloud using Harmony) so I tried to disconnect from Soundcloud on the settings and then relog but I faced to this issue #151 and I tried to upgrade the program. After that the feed was still blank.
I did a big update of my system today so maybe yesterday I was using the 0.4.5 version, I could try to downgrade to it if you want.
I'm following lot's of users: https://soundcloud.com/unixfox/following
My stream on the webapp:
![selection_140](https://cloud.githubusercontent.com/assets/4016501/23823813/d32fb552-066a-11e7-9675-bc2b924406a4.png)

**Comment by vincelwt** [comment]
Mmh, it should indeed show some tracks on the feed tab. I'm curious to see if it works with 0.4.5! I don't remember changing anything related to the feed between 0.4.5 and 0.4.7

**Comment by unixfox** [comment]
It's working great using the 0.4.5 version, proof:
![harmony_141](https://cloud.githubusercontent.com/assets/4016501/23823905/8e83473c-066c-11e7-870e-0b2efeb8e0cc.png)
It may be related to the API keys that you changed (?)

**Comment by vincelwt** [comment]
The API keys haven't really changed, only the server hosting them. If something were wrong with them, I don't think you would even be able to see your liked tracks. I'll check what else exactly changed between the versions see if I can fix it.

**Comment by vincelwt** [comment]
Found the bug! :) Simply a ! missing from the refactoring to ES6. I'm not using SoundCloud these days so I hadn't noticed it. Thanks for reporting, we'll be available with next release

**Comment by unixfox** [comment]
Nice, thank you for taking the time to resolve this issue.

I'll close the issue when I'll be able to test if it works again.

**Comment by vincelwt** [comment]
No problems. I still have some other stuff to implement (great stuff coming) before 0.5 (next release) so it will be available a few days

**Comment by vincelwt** [comment]
Should be fixed with 0.5.0 :)

**Comment by unixfox** [comment]
Is it possible to add binary archive like you did for the version 0.4.7 (`harmony-0.4.7.tar.xz`)?

**Comment by vincelwt** [comment]
@unixfox I removed the tar.xz build because there was already the .AppImage build (http://appimage.org/)., which should work with almost every distributions. Don't the .AppImage work on your system?

Unfortunately yes, Harmony is now closed-source, but I hope it will free me more time to work on it and make it way better.

**Comment by unixfox** [comment]
It's works on mine but I'm using a community package manager (https://wiki.archlinux.org/index.php/Arch_User_Repository) on ArchLinux who use directly the binary provided by the `tar.xz`, you can check this here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=harmony-player#n18. And I think it's easier for the maintainer (kusti8) of the package `harmony-player` to use the archive instead of the .AppImage because the only thing that he has to do is to change the number version.

**Comment by vincelwt** [comment]
Um ok I see. I'll build the tar.xz version this afternoon :)
However the maintainer of the repo is going to need to change the name of the file a little because it will now be `harmony-0.5.0-x64.tar.xz` (with the arch). 

About the original issue, were you able to test?

**Comment by unixfox** [comment]
Yes and the feed works perfectly.
Thank you for everything!
