### ISSUE TITLE
Disable windows notification sound

### ISSUE THREAD

**Issue by jessehouwing** [vincelwt/harmony#159]
In Windows 10 the app sends a notification every time a track changes, Windows plays a notification sound every time this happens. It's possible to sens an additional flag with notifications to suppress the sound: http://stackoverflow.com/a/37434900/736079

As a workaround, I've disabled the notification sounds manually in the settings (rightclick a notification in the notification center and edit it's settings):

![image](https://cloud.githubusercontent.com/assets/4173387/24147793/2de06504-0e3c-11e7-8631-b0790061b041.png)

**Comment by vincelwt** [comment]
Hi,
Notification sound is indeed annoying when playing music.
However Harmony isn't written in c++, so your link isn't applicable.
I'll take a look if it's possible to do with Electron :)

**Comment by vincelwt** [comment]
Ok it should be disabled now. I can't test on Windows right now, but I'm letting this issue open so you can report when next release is out.

**Comment by vincelwt** [comment]
Should be ok on Windows now with 0.5.1 :)
