### ISSUE TITLE
Download links on the website

### ISSUE THREAD

**Issue by igniuss** [vincelwt/harmony#160]
Just a little heads up, the download links on the website are incorrect
`https://github.com/vincelwt/harmony/issues/releases/download/v0.5.0/harmony-0.5.0-* `
while it _should_ be 
`https://github.com/vincelwt/harmony/releases/download/v0.5.0/harmony-0.5.0-*`

**Comment by vincelwt** [comment]
Thanks a lot for reporting! I made a bulk search/replace on all the files and forgot to exclude this one.

**Comment by vincelwt** [comment]
Fixed.
