### ISSUE TITLE
Permission denied on Artworks causing not loading the playlist

### ISSUE THREAD

**Issue by silverspectro** [vincelwt/harmony#164]
harmony.log

We are on a -win32- system
Testing internet...
https://soundcloud.com/connect?client_id=xxx&redirect_uri=http://localhost&response_type=code&display=popup
https://soundcloud.com/connect?client_id=xxx&redirect_uri=http://localhost&response_type=code&display=popup
Testing internet...
Error fetching data. undefined
Testing internet...
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\defd59657b05e97c93f1334e737ec6ef.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\defd59657b05e97c93f1334e737ec6ef.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\defd59657b05e97c93f1334e737ec6ef.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\defd59657b05e97c93f1334e737ec6ef.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\e4ec8fb5ce64a4a7752f932e592fe629.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\e4ec8fb5ce64a4a7752f932e592fe629.jpg' }
{ Error: EPERM: operation not permitted, open 'C:\Users\Ciro\AppData\Roaming\Harmony\Artworks\defd59657b05e97c93f1334e737ec6ef.jpg'
  errno: -4048,
  code: 'EPERM',
  syscall: 'open',
  path: 'C:\\Users\\Ciro\\AppData\\Roaming\\Harmony\\Artworks\\defd59657b05e97c93f1334e737ec6ef.jpg' }
Latest release is v0.5.0 and we're running undefined
Error fetching data. undefined
Latest release is v0.5.0 and we're running undefined

**Comment by silverspectro** [comment]
This causes the software to block  the loading and i don't have my libraries

**Comment by vincelwt** [comment]
As a workaround (for the time I fix it) you could try running Harmony as an administrator, it should then have sufficient rights to write in this folder.

**Comment by silverspectro** [comment]
Administrator rights don't solve the problem, i still have the EPERM error.
In think that it is because files are read at the same time.

**Comment by vincelwt** [comment]
OK i'm booting a Windows to try and fix it

**Comment by vincelwt** [comment]
Just tried with a local album with artworks on Windows 10 and I don't have any issues :/
Could you try deleting the 'C:\Users\Ciro\AppData\Roaming\Harmony' folder then start Harmony again?

**Comment by vincelwt** [comment]
Anyway I'll try to better handle the error so worst case is your local files cover aren't showing but you can still access your library.

**Comment by silverspectro** [comment]
It works !
Deleting th Artwork folder removed the bug, but as i wanted to reconnect to Soundcloud, Harmony reloaded my entire library and the bug happened again.

**Comment by vincelwt** [comment]
Are you using the Avast antivirus? It seems to be causing [some related issues](https://www.webfoobar.com/node/39) and disabling it might help.

**Comment by vincelwt** [comment]
With next release, Harmony _should_ now better handle this error.

**Comment by vincelwt** [comment]
0.5.1 is out, could you try and report if you still see the error ?

**Comment by silverspectro** [comment]
No error  this morning on the new version ! seems ok.
tested on Windows 8.1 and 10.
Thanks for the fix 👍

**Comment by vincelwt** [comment]
Great!
