### ISSUE TITLE
Favorites are not kept on Windows 10

### ISSUE THREAD

**Issue by silverspectro** [vincelwt/harmony#166]
It seems that my favorites song (local or remote) are not kept.
I juste tried to put a song as a favorite, closed Harmony and relaunched, and nothing there on the favorites folder.

Were are the favorites kept ?
Is there a way for me to check why ?

Thanks,

**Comment by vincelwt** [comment]
Hi,
What services did you try to like?

Did you tried refreshing the library when you relaunch harmony? It might be a bug of not saving before closing.

**Comment by silverspectro** [comment]
It was a local song that i tried to like.
Yes i tried refreshing the library and not refreshing it, same thing happen.
I made another test just before sending this message, still with a local song, and same thing, the song is no longer in my favorites when i open Harmony again.

**Comment by vincelwt** [comment]
Ok I'll take a look

**Comment by vincelwt** [comment]
Sorry for the late answer, I've checked it out and can confim the bug, I'm working on it.

**Comment by vincelwt** [comment]
Fixed, will be available with next release.

**Comment by vincelwt** [comment]
Should be fixed with 0.6!
