### ISSUE TITLE
No sound issues

### ISSUE THREAD

**Issue by marcelofrau** [vincelwt/harmony#167]
Hello, 

I am using LXDE as my default system enviroment and I am on Linux Mint 17. Unfortunately no sound is getting out from harmony player. 

I use a USB headphone to listen my music, perhaps it has something to do with this. 

My main soundcard is not used. There is a way to force the audio to output on a specific device?

**Comment by vincelwt** [comment]
Hey,

Seems more like an issue with your system, did you try opening the sound settings and toying with the available options? Also, do you have issues with others programs like Chromium for example?

**Comment by marcelofrau** [comment]
All my other programs seems to work fine, chrome, spotify, clementine and every other program that I have tried are working normally.

There is no sound options in the harmony settings. A lot of other audio related programs have an option to choose the output device. (note that I have not changed any option in any program to make sound output from my headphone)

**Comment by vincelwt** [comment]
Hi, is this still happening with 0.7.0 ?
