### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by biondi53** [vincelwt/harmony#168]
https://www.virustotal.com/es-ar/file/7599cc716aee92c2a34010f50b20303884310c6a2a7802687e0468ce81175891/analysis/

**Comment by vincelwt** [comment]
Hey,
This was already discussed at #19, there doesn't seems to be anything to do, asar packaging must be causing this. I'll add this info to the faq, but I don't think I can do anything more.

**Comment by biondi53** [comment]
Sorry

**Comment by vincelwt** [comment]
No problems. I added it to the faq.
