### ISSUE TITLE
Spotify Quality 

### ISSUE THREAD

**Issue by Glubb** [vincelwt/harmony#169]
I'm not sure what's causing it, but some songs play at a very low quality at random. Perhaps a quality control feature could be added.

**Comment by vincelwt** [comment]
Hey,
As the Spotify plugin is playing from YouTube, it may sometimes find videos with a lower quality. I'm thinking about adding an option to select the best available audio source from YouTube, if your connection can handle it.

**Comment by vincelwt** [comment]
Will be available with next release.

**Comment by vincelwt** [comment]
Available with 0.6.0 in the settings :)
