### ISSUE TITLE
Can't paste password into web UI

### ISSUE THREAD

**Issue by lifeiscontent** [vincelwt/harmony#17]
Hi, using something like 1password or lastpass is impossible with Harmony. From the login with Spotify and other logins I cannot right click to paste or cmd+v to paste (on mac) my password into the UI.

Please fix this, I'd love to use this app!

**Comment by vincelwt** [comment]
I can't reproduce the issue, on Linux copy-paste works fine.
Must be specific to Macs 
If anyone can confirm this issue on Mac ?

**Comment by digitalknk** [comment]
I am also having this issue. I tried pasting just my username into the login prompts that come up, and they will not paste into the text form.

**Comment by vincelwt** [comment]
Ok, I think I found why: we need to add a menu template to enable shortcuts.
https://pracucci.com/atom-electron-enable-copy-and-paste.html
