### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Glubb** [vincelwt/harmony#170]
I'm not sure what's causing it, but it's running pretty high at 1.4gb ram
Ubuntu 16.04

**Comment by vincelwt** [comment]
Hey,
There must indeed be a leak, as I'm running at ~300mb on Ubuntu.

What services are you using?
If you are using local files, what is the size of your library (in gb) ? 

Also, could you send a screenshot of your task manager with the details of Harmony's processes (might also show up as electron) ? Just to check from which process is coming the leak.

**Comment by vincelwt** [comment]
Hey, could you try with 0.6.0? Harmony now uses a db to store data, not in RAM anymore.

**Comment by vincelwt** [comment]
Closed for lack of information/update
