### ISSUE TITLE
Sorting problems

### ISSUE THREAD

**Issue by yarygin** [vincelwt/harmony#175]
There is no way to cancel sorting in list. Also I can't reverse sorting. It works ASC only .

**Comment by vincelwt** [comment]
You can click on your current tab to reset sorting.
I'll probably integrate DESC sorting in next release

**Comment by yarygin** [comment]
Ok. I just wanted to help the project with come bug reports:-)

**Comment by vincelwt** [comment]
Appreciated ;)

**Comment by vincelwt** [comment]
DESC sorting now working with 0.7 ;)
