### ISSUE TITLE
support for general purpose param object[]

### ISSUE THREAD

**Issue by friuns2** [vincelwt/harmony#177]
i'm integrating harmony with jurrassic javascript runtime intepreter and i stuck at problem

for example original method is test(int a, string b)

but i would like to patch it with testPrefix(object[] o) so o[0]=a and o[1]=b

but its not possible currently in harmony

**Comment by vincelwt** [comment]
Harmony is based on Electron and cannot be run on something else due to the Electron dependencies.

I'm not sure what you are trying to do, maybe wrong project ?

**Comment by friuns2** [comment]
yeah wrong project sorry
