### ISSUE TITLE
Spotify - Plays incorrect track

### ISSUE THREAD

**Issue by BartoszKaszewczuk** [vincelwt/harmony#179]
Playing [`Blank & Jones - The Breeze`](http://open.spotify.com/track/0b1WjbZYFx4Jvxzr6a8OoV) from Spotify's "My Tracks" actually plays [`Taylor Swift - Blank Space`](https://play.spotify.com/track/580t2NTEMOuCHV1sN3uhyD). 

During playback however the track is correctly scrobbled to Last.fm as `Blank & Jones - The Breeze`. Artwork and Artist + Track Name is correctly displayed in app's header as well as in "system tray" as `Blank & Jones - The Breeze` (albeit "system tray" doesn't print `&` char). 
This behaviour continues between restarts and occurs with other tracks as well so seems like an issue with track matching.
Rather bizarre mixup.

No errors in console.
```
utils.js:7 Testing internet...
utils.js:54 Latest release is v0.6.0 and we're running 0.6.0
main.js:259 Fetching services data over.
utils.js:45 Checking for updates...
utils.js:7 Testing internet...
utils.js:54 Latest release is v0.6.0 and we're running 0.6.0
main.js:259 Fetching services data over.
```

OS X 10.11.6
Harmony v0.6.0 Mac

**Comment by vincelwt** [comment]
This is an issue with the "&" character during the YouTube matching algorithm, which I recently fixed! Should be okay with 0.7.0 coming very soon

**Comment by vincelwt** [comment]
Could you try with 0.7.0 ? Should now be better working

**Comment by BartoszKaszewczuk** [comment]
Retried with 0.7.0 and it looks like it introduced a regression and none of the tracks from Spotify play anymore. Every attempt throws following stack trace in console. SoundCloud works fine however.
```
/Applications/Harmony.app/Contents/Resources/app.asar/app/js/plugins/youtube.js:228 Uncaught ReferenceError: error is not defined
    at apiRequest (/Applications/Harmony.app/Contents/Resources/app.asar/app/js/plugins/youtube.js:228)
    at Request.request [as _callback] (/Applications/Harmony.app/Contents/Resources/app.asar/app/js/plugins/youtube.js:18)
    at Request.self.callback (/Applications/Harmony.app/Contents/Resources/app.asar/node_modules/request/request.js:188)
    at emitTwo (events.js:106)
    at Request.emit (events.js:191)
    at Request.<anonymous> (/Applications/Harmony.app/Contents/Resources/app.asar/node_modules/request/request.js:1171)
    at emitOne (events.js:96)
    at Request.emit (events.js:188)
    at IncomingMessage.<anonymous> (/Applications/Harmony.app/Contents/Resources/app.asar/node_modules/request/request.js:1091)
    at Object.onceWrapper (events.js:290)
```

**Comment by vincelwt** [comment]
Oops there was an dumb issue preventing to see the real error, fixed now could you redownload Harmony and show the new console output ?

**Comment by BartoszKaszewczuk** [comment]
Download page 404s now.

**Comment by vincelwt** [comment]
Sorry, fixed.

**Comment by BartoszKaszewczuk** [comment]
Playing from Spotify now causes Harmony to iterate over entire Spotify playlist in attempt to play the next track with each failing and throwing 400 errors in console.

```js
player.js:89 Object {code: 400, errors: Array[1] {0: Object length: 1, __proto__: Array[0] message: "Bad Request"}, __proto__: Object}
streamObtained @ player.js:89
```

**Comment by vincelwt** [comment]
In the console, can you expand the `errors: Array[1] `to see more details ?

**Comment by BartoszKaszewczuk** [comment]
![screen shot 2017-08-04 at 18 58 46](https://user-images.githubusercontent.com/1344624/28980804-16fb1ade-7947-11e7-96e3-e740085f1dca.png)

**Comment by vincelwt** [comment]
Thanks, seems like an error with the YouTube API key. Weird because I can't reproduce with the same key. I'll take a closer look

**Comment by vincelwt** [comment]
Just in case, did you refresh your library at least once after updating Harmony ? It is needed to get the new API keys

**Comment by BartoszKaszewczuk** [comment]
Yes, I tried both refreshing the library and wiping cache and starting all over. Neither fixed the issue.

**Comment by vincelwt** [comment]
Just tried with a different computer and can confirm the bug. Working on it.

**Comment by vincelwt** [comment]
Alright this was an issue server-side due to the server hosting the keys out of sync with my local development server, it should work after refreshing your library !
Thanks for reporting & helping :)

**Comment by BartoszKaszewczuk** [comment]
Can confirm it working now. `Blank & Jones - The Breeze` is immediately skipped over now which seems like a reasonable behaviour considering that the track is not available on YouTube.

**Comment by vincelwt** [comment]
Nice to hear!
