### ISSUE TITLE
Feature request: Deezer and Pandora integration

### ISSUE THREAD

**Issue by brunomiguel** [vincelwt/harmony#18]
Hi.

Just came across Harmony and I find it really interesting. I like the Spotify and Soundcloud integration, but I believe it would also benefit from Deezer and Pandora integration - although I won't be able to submit a pull request since I'm not a programmer.

Keep the good work.

**Comment by vincelwt** [comment]
Hi @brunomiguel 

Deezer is planned.

As for Pandora, it isn't available at the moment in my country (France) so I can't work on it :/

**Comment by brunomiguel** [comment]
Nice news, @vincelwt :) Pandora can be accessed via VPN or proxy (a nice feature to have in the app).

**Comment by azsde** [comment]
@vincelwt  Do you have an estimated ETA for Deezer integration ?

**Comment by romain-poirson** [comment]
Nice news, @vincelwt :)

**Comment by vincelwt** [comment]
@azsde I've just started working on the plugin system, which will allow more services to be included. I should finish it in more or less 2 weeks depending on my free time

**Comment by vincelwt** [comment]
I've started working on the Deezer plugin.

**Comment by brunomiguel** [comment]
Awesome news! :D Can't wait for the commits.

**Comment by azsde** [comment]
Any eta for the Deezer plugin ? Do you need help with something ? :)

**Comment by vincelwt** [comment]
@azsde I have quite a lot of work to do this week, and won't be able to work a lot on Harmony. I don't like to give any date but it should be over this weekend or next weekend

**Comment by vincelwt** [comment]
@azsde I finished the plugin, but am still hunting for some bugs and improvements. I'll push the work to the repo tonight or tomorrow.

**Comment by azsde** [comment]
Could you add multi-profile support for the Deezer plugin ? We have a family account and have different profile on the same account.

**Comment by vincelwt** [comment]
@azsde I'm not sure this is possible, as everything depends on the Deezer API, which doesn't mention anything about it. Did you already tried and can confirm it doesn't works with current implementation ?

**Comment by vincelwt** [comment]
Closing as it it available with 0.4

**Comment by azsde** [comment]
Deezer plugin is not working at all for me :(

I log in, but that's it, search won't give me any results, and playlists section is empty.

**Comment by vincelwt** [comment]
@azsde Can you see the Flow in Discover section ? And the loved tracks playlist ? 
Search is (for now) only for filtering current playlist.

**Comment by azsde** [comment]
I can see only data from the main profile, not the secondary ones

**Comment by vincelwt** [comment]
@azsde So you can confirm it works at least with the main profile ? You can access Flow and loved tracks playlists ?
