### ISSUE TITLE
Harmony can't fetch my YouTube playlists

### ISSUE THREAD

**Issue by unixfox** [vincelwt/harmony#180]
Harmony can't fetch my YouTube playlists and throw me an error:
![harmony_186](https://user-images.githubusercontent.com/4016501/28995946-960c5e96-79f6-11e7-91d3-2e39cc0ce08e.png)
```
We are on a -linux- system
utils.js:45 Checking for updates...
utils.js:54 Latest release is v0.7.0 and we're running 0.7.0
utils.js:7 Testing internet...
main.js:294 Error fetching data. Objectcode: 404errors: Array[1]0: Objectlength: 1__proto__: Array[0]message: "The playlist identified with the requests <code>playlistId</code> parameter cannot be found."__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()
Promise.all.then.catch @ main.js:294
_tickCallback @ internal/process/next_tick.js:103
```

**Comment by vincelwt** [comment]
For now the YouTube plugin only supports liked tracks (I'll try to support playlists in the future), but the error shouldn't happen. Working on it !

**Comment by vincelwt** [comment]
The error should be fixed by redownloading 0.7.0 ;)

**Comment by unixfox** [comment]
You should push a minor update like 0.7.1 or 0.7.0.1 instead of recreating the archive because firstly that's how every program does and secondly recreate the archive breaks the systems who rely on the checksum of the archive, for example the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=harmony-player#n24) was invalid but fortunately I fixed it (because I'm recently the maintainer of the package).

Harmony works perfectly without the bug, thank you.

**Comment by vincelwt** [comment]
@unixfox You're right thanks! Didn't knew it broke these stuff
