### ISSUE TITLE
harmony hangs after opening, post reddit/local music connection

### ISSUE THREAD

**Issue by hamishmaku** [vincelwt/harmony#181]
as it says in the title, the app opens and shows the refreshing icon animating, but shortly after freezes and has to be closed.

running version 7.0 64 bit Debian Sid, no terminal output?

this application has good potential, I would like a desktop-level app that runs soundcloud - are there plans to include search functionality? would be good to generate lists based on keywords/tags etc.

this would also be useful in spotify and youtube.

thanks!

**Comment by vincelwt** [comment]
Hi!

You can see the output by opening the devtools with Ctrl+Alt+I, then _console_ tab. This would be very useful if we can see errors!

Could you try with only your local files see if it hangs, or only with Reddit ? That way we can see if a specific service is causing the hang.

About the search, it is already available: type something in the search box, it will first filter your tracks but once you press _enter_ it'll make a global search 😉 This works with  the Spotify, SoundCloud, YouTube, Deezer, Hype Machine & Google Play music plugins.

**Comment by hamishmaku** [comment]
when I start with a new config I get the same behaviour - so it might not be related to the services at all?

this is the console output..

Error fetching data. Error: connect EMFILE 151.101.129.140:443 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:1022)
    at exports._exceptionWithHostPort (util.js:1045)
    at connect (net.js:884)
    at emitLookup (net.js:1013)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81)
Promise.all.then.catch @ main.js:292
_tickCallback @ internal/process/next_tick.js:103
utils.js:7 Testing internet...
VM461:1 Uncaught SyntaxError: Unexpected token 

thanks for the quick response!

**Comment by vincelwt** [comment]
Seems like an error with your local files, close to #106 .
How big is your library (in GB) ? 
you can try with disconnecting the local files plugin by opening the settings, _plugins_ tab, 'Manage connected services' and then clicking on your local folder and simply closing the window, without any folder selected.

**Comment by hamishmaku** [comment]
uh, maybe 120 gb? I can't access the settings  menu as the application
crashes shortly after startup. I've tried removing the harmony folder in
.config, but it still crashes.

thanks again for helping me with this.

**Comment by hamishmaku** [comment]
see, removing configstore and testing now

**Comment by hamishmaku** [comment]
yeah it opens without local files, and that's fine I have other players for
local stuff.

however it won't load reddit atm, giving this (oblique) error:

Error fetching data. 403
Promise.all.then.catch @ main.js:292


is there a chance you'll add an option to either increase the maximum
number of search results, or give us a "infinite scroll" style result pane?
the 20 or so provided mean you have to be super specific with what you're
searching for.

**Comment by vincelwt** [comment]
So the issue was indeed the large library :/ There as been a lot of persons with this bug but I haven't still figured out a solution.

About the 403 issue, is there anyway you can expand the error in the console of devtools to see more details ? A 403 error could have a bunch of origin and it would help to have more details.

For the limited search results, which service are you using for the search and would like to see more results ?

**Comment by vincelwt** [comment]
Could you try again with the latest version ? I changed the way it fetches local tracks so maybe it will help
