### ISSUE TITLE
Settings window keeps re-opening

### ISSUE THREAD

**Issue by DLMousey** [vincelwt/harmony#182]
Earlier today (about 3 hours ago) i had a notification from Harmony saying there was a new version available, Went to visit the website to download it and the site was down with a bad gateway (Still appears to be down as of 13:00).

Opening Harmony presents me with the settings window and none of my usual services signed in, When i try to log in to those services it throws an error saying "Error connecting to internet" (network connectivity is fine and nothing's blocking Harmony from connecting), When you attempt to close the settings window it re-opens, See gif;

![Gif of settings window](https://puu.sh/x7okw/c0a500b72a.gif)

Possibly dumb question but is this related to the Harmony site being down? Or is it a bizarre coincidence?

Encountered on Windows 10 (Build 15063), 
Not sure which Harmony version, I'm assuming latest if a new update isn't available

**Comment by vincelwt** [comment]
Hi! Thanks for reporting, yes it is because of the site being down, as Harmony tests internet by pinging the same domain. What's weird is it was working fine last night. I'm working on it!

**Comment by vincelwt** [comment]
Alright there was an issue server side causing the 502, now fixed, can you confirm Harmony is working again ?

**Comment by DLMousey** [comment]
That's all working fine again now :)
Could it be worth making it configurable where it pings to test an internet connection if the Harmony one fails? Then you can still get access to your libraries if there's a problem with the Harmony site.

Or do you have to go through the Harmony site as part of the authentication to the third party services?

**Comment by vincelwt** [comment]
Yes, the website returns API keys so Harmony can make operations with the third-party services. It would sure be better to use google.com as the ping test, but first I'd have to make Harmony store the API keys, which isn't a good thing I think. 

I've also set up a downtime alert so a long downtime like today doesn't happen again.
