### ISSUE TITLE
Harmony not listing reddit playlist

### ISSUE THREAD

**Issue by rotojp** [vincelwt/harmony#186]
Harmony is connected to reddit account, however no of the "subreddits to show" are to be found anywhere.  Furthermore, a message ```Error. Retry later``` is displayed. Console only shows the following message:
```
main.js:301 Error fetching data. 403
Promise.all.then.catch @ main.js:301
_tickCallback @ internal/process/next_tick.js:109
```

**Comment by vincelwt** [comment]
Hey!
Could you send the content of the subreddits to show text box ?

**Comment by rotojp** [comment]
'Course! Haven't changed them from the default though..
`listentothis,futurebeats`

**Comment by vincelwt** [comment]
Weird :/ Do you have any other services activated ?

**Comment by rotojp** [comment]
Not entirely sure how it would be possible to replicate the problem..
Currently the following services are activated:
- [x] Reddit
- [x] Spotify

**Comment by vincelwt** [comment]
Could you try disabling Spotify see if the 403 error is still happening ?

**Comment by jabui** [comment]
@vincelwt - Problem is your Reddit username is hardcoded in the plugin
https://github.com/vincelwt/harmony-plugins/blob/master/reddit.js#L108

**Comment by vincelwt** [comment]
@jabui Lol, thanks for spotting that. I feel dumb ^^ Must have left it out when I was trying some things, will be fixed.

**Comment by vincelwt** [comment]
0.8 is out, and this issue should now be fixed :)
