### ISSUE TITLE
Unable to Search

### ISSUE THREAD

**Issue by SyxP** [vincelwt/harmony#188]
When typing anything into the search bar, I get `Uncaught TypeError: Cannot read property 'split' of undefined
    at HTMLInputElement.oninput (index.html:53)`

I am running this on Antergos (Arch Linux) and on version 0.7.2 of Harmony.

**Comment by SyxP** [comment]
I fixed it, it looks like you have to connect Last FM and Youtube to work.

**Comment by vincelwt** [comment]
Weird 🤔 what services did you have enabled before ?
