### ISSUE TITLE
“Harmony.app” can’t be opened

### ISSUE THREAD

**Issue by isdn** [vincelwt/harmony#189]
Hello,

I tried to run in on OSX, and faced the following - `“Harmony.app” can’t be opened because it is from an unidentified developer.`.
I downloaded the DMG from your site (the links was "https://github.com/vincelwt/harmony/releases/download/v0.7.2/harmony-0.7.2-mac.dmg").

**Comment by vincelwt** [comment]
Hi!
This isn't really an issue with Harmony but the way MacOS "protects" its users.

See [this article](http://osxdaily.com/2012/07/27/app-cant-be-opened-because-it-is-from-an-unidentified-developer/) for how to open
