### ISSUE TITLE
Allow searching of providers like youtube and soundcloud

### ISSUE THREAD

**Issue by danielzfranklin** [vincelwt/harmony#192]
It is inconvenient to have to open youtube or soundcloud only to add a video to a playlist before I can use it in harmony. When I search, a "cloud" icon appears, which made me think clicking on it would run the search online. When I do so, nothing happens, however. 
<img width="178" alt="screen shot 2017-10-23 at 12 12 17 pm" src="https://user-images.githubusercontent.com/10361846/31908371-7857e068-b7eb-11e7-8052-088e4d053a70.png">

**Comment by vincelwt** [comment]
Hey! This is indeed weird, as clicking the cloud icon (or pressing enter) should run the search online. What services do you have enabled ?

**Comment by vincelwt** [comment]
I think this is an issue that happened because of the bug removed by 0.8.2. Could you confirm it's working now?
