### ISSUE TITLE
Allow copying songs from a remote provider to the local files provider

### ISSUE THREAD

**Issue by danielzfranklin** [vincelwt/harmony#193]
If I have a song on youtube and am playing it in the interface, I would like to be able to download the song into the local provider also enabled.

**Comment by vincelwt** [comment]
Hey!
This is something I would really like to implement but unfortunately is strictly prohibited by the platforms (Soundcloud, Spotify, Deezer, etc…). The only way it could be done is through a third-party plugin not integrated in the app but first I have to improve the plugin system capabilities.

So I'm closing this for now but it may be implemented in some way in the future.
