### ISSUE TITLE
Startup error.

### ISSUE THREAD

**Issue by Foxylizer** [vincelwt/harmony#194]
When starting Harmony in Windows 10 Fall Creators Update, I get this error.

![image](https://user-images.githubusercontent.com/29559592/32511594-dde497c6-c3b9-11e7-97ea-d58ee48395ac.png)

This happens every time.

**Comment by vincelwt** [comment]
Hey,
Did you open once Harmony with admin privileges?
The module Harmony is using to store configurations seems to have troubles with its rights to modify the config file.
You could try removing the

**Comment by Foxylizer** [comment]
That worked, thanks!
