### ISSUE TITLE
Cryptocurrency payment option for buying Harmony license

### ISSUE THREAD

**Issue by unixfox** [vincelwt/harmony#196]
2017 is the year of cryptocurrency. Lots of websites that offers services are integrating the cryptocurrencies in their payment options. Moreover, if someone buys a license at $40 the next month these $40 will become higher because the price of cryptocurrencies are growing rapidly.

I give you a list of some cryptocurrency payment gateway if you are interested:

| Name | Cryptocurrency support | NodeJS library |
|------|-------------------| ----- |
| [Bitpay](https://bitpay.com/bitcoin-payment-gateway-api) | Bitcoin | [Github](https://github.com/bitpay/node-bitpay-client) |
| [Coinbase](https://www.coinbase.com/merchants) | Bitcoin | [Github](https://github.com/coinbase/coinbase-node) |
| [CoinPayments](https://www.coinpayments.net/) | [70 digital currencies (including Bitcoin)](https://www.coinpayments.net/supported-coins) | [Github](https://github.com/OrahKokos/coinpayments) |
| [Blockonomics](https://www.blockonomics.co) | Bitcoin | [Github](https://github.com/sgsshankar/blockonomics-node) |
| [Blockchain.info](https://blockchain.info/api/api_receive) | Bitcoin | [Github](https://github.com/ortexx/blockchain-payments) |
| [Coinify](https://coinify.com) | [15 digital currencies (including Bitcoin)](https://support.coinify.com/Knowledgebase/Article/View/119/5/which-blockchain-currencies-are-you-currently-supporting-for-payments) | n/a |
| [Gocoin](https://gocoin.com) | [Bitcoin, Litecoin, and Dogecoin](https://gocoin.com/blockchain) | [Github](https://github.com/GoCoin/gocoin-js) |

This list is incomplete because there are a ton of others cryptocurrency payment gateway.

Please be aware that you should support multiple cryptocurrencies because not everyone uses Bitcoin and Bitcoin has his network congested: https://cointelegraph.com/explained/bitcoin-scaling-problem-explained and https://www.youtube.com/watch?v=WpnztqpVhME (French video).

PS: I'm an ethereum enthusiast.

**Comment by vincelwt** [comment]
Hey! Thanks for the well redacted issue, I'm a crypto enthusiast too so I totally agree with you :P 

I already had plans to support Bitcoin via Stripe which would make the integration very easy, but it's true that it should allow more currencies and Bitpay sound like a good payment gateway to get started with, I'll give it a shot when I have some time!

**Comment by unixfox** [comment]
That's a good idea and a bad idea to start with Bitpay, I explain why.
That's a good idea because Bitpay is easy to integrate and written in NodeJS.
But that's a bad idea because Bitpay doesn't support Segwit and they are implementing a software that will run off the chain of Bitcoin: https://www.reddit.com/r/btc/comments/7g82c6/bitpay_invoices_will_soon_require_payment/, they are implementing a work around because the blockchain of Bitcoin is congested.

**Comment by vincelwt** [comment]
Sorry for late reply! And thank you for taking the time to explain Bitpay.

At the end, I'll probably go with CoinPayments as they seem to have the larger support of cryptos ;)

**Comment by vincelwt** [comment]
It's now possible to buy licenses with cryptocurrencies ;) I ended up using Coingate, they had the simplest API and the most comprehensive checkout flow imho. Licenses are now sold through my other project, [Nucleus.sh](https://nucleus.sh).

**Comment by unixfox** [comment]
@vincelwt That's pretty great, the amount of cryptocurrencies supported is huge!
PS: I wish you the best for your project :).
