### ISSUE TITLE
Harmony freezes on Ubuntu 17.10 

### ISSUE THREAD

**Issue by scott1958** [vincelwt/harmony#198]

**Comment by vincelwt** [comment]
Hey, I had a 503 trying to answer your mail, so here is what I sent you:

_Hi,
Very weird, could you send me a screenshot of the log (Ctrl+alt+I, 'console' tab) ? That’d be a great help to see if there’s an issue reported by Harmony.
Also, did you connect your local library?
If so, how big is it? and could you try removing it and using only another cloud plugin?
I’m sorry about that!
Cheers,_
