### ISSUE TITLE
Doesn't Continue Playing

### ISSUE THREAD

**Issue by ghost** [vincelwt/harmony#199]
When a track is done playing, Harmony does NOT move on to the next track on the list.

**Comment by vincelwt** [comment]
Hi! Are you running 0.8.2? Also what platform please?
Could you make sure the experimental caching option is disabled?

**Comment by ghost** [comment]
Yes, I am running version 0.8.2.
The platform I am running is Windows 10 Fall Creators Update. 
The experimental caching is disabled, should I enable it?

**Comment by vincelwt** [comment]
Mm could you try enabling it, try if it works, if not disable it again see if it now works?
Someone had to enable it/disable it for the changes to take effect

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/26362558/34003645-d436ab02-e0c3-11e7-8f1b-065345d9f01e.png)

Your program is just sad, in the past 13 hours, it has not been able to load. 
Yes, I have tried the refresh button. I already tried re-installing it. 
What's wrong with your program, do NOT release another update until all this shit is fixed, been pissing me off since version 0.7.1

**Comment by vincelwt** [comment]
First of all, I have no obligation whatsoever to you or anyone else regarding releases. 
If you don't like using Harmony, either help improve it or don't use it.
I won't tolerate this kind of talk, so issue closed.
