### ISSUE TITLE
Spotify lists not loading

### ISSUE THREAD

**Issue by marcossangon96** [vincelwt/harmony#20]
I have 17 playlists in Spotify and when I load Spotify music only loads 8 playlists and some of them are empty.
Added: I have Spotify Premium.

What to do?

Also, is there anyway to load local files ordered by folders instead of showing all songs?

**Comment by BenDz** [comment]
I was about to open the same issue. 
I have a *few* more playlist in Spotify :)
![2016-09-08_09h40_48](https://cloud.githubusercontent.com/assets/3985936/18341068/86a911a4-75a8-11e6-86fd-32b2dbb84d18.png)

**Comment by vincelwt** [comment]
When you restart the app, are the same playlists being reloaded ?

I'll try to reproduce the issue

And no, for now you can't control how to sort your file but sorting by Album, Artist or track name is close on my todo list.

**Comment by marcossangon96** [comment]
Yes, when I restart, there are the same playlists and the same songs, still don't loading all of them. And some of the lists are completely empty.

**Comment by vincelwt** [comment]
I tried replicating the issue by adding 20 playlists, but everything's is loading fine.
Did you find a pattern with the playlists showing ? Are these only the playlists you created and not the ones you follow on Spotify ?

Could be related to [this](https://github.com/spotify/web-api/issues/87) or [this](https://github.com/spotify/web-api/issues/3)

**Comment by vincelwt** [comment]
Ok I think the problem came from a missing scope in Spotify Oauth.
I'll try to release a version soon so you can try. You will need to disconnect from Spotify and reconnect.

**Comment by vincelwt** [comment]
@marcossangon96 and @BenDz Could you confirm this is solved works in 0.2.4 ? Thanks 
(Don't forget to disconnect and reconnect from Spotify)

**Comment by BenDz** [comment]
Hi @vincelwt , just refreshed it and it works! Thanks!

**Comment by vincelwt** [comment]
Great :)

**Comment by marcossangon96** [comment]
@vincelwt Fixed!! Thank You!
