### ISSUE TITLE
Spotify and Deezer doesnt works

### ISSUE THREAD

**Issue by rodriarevalo** [vincelwt/harmony#200]
I can hear anything on latest version for windows.

**Comment by vincelwt** [comment]
Hi! 
Could you try enabling the "_Use the old, less power hungry, playing mechanism_" option and see if it helps?
Thanks.

**Comment by rodriarevalo** [comment]
I cant find that option, sir.

**Comment by vincelwt** [comment]
Sorry,
Preferences -> plugins -> YouTube
