### ISSUE TITLE
Deezer only importing the first 25 playlists (in alphabetical order)

### ISSUE THREAD

**Issue by TheSHEEEP** [vincelwt/harmony#202]
And another one for Deezer.
For some reason, only the first 25 playlists are being imported, see the screenshot below:

![image](https://user-images.githubusercontent.com/1766205/35765931-082b73e4-08d7-11e8-911a-d5c59f67f9d7.png)

As you can see, it only goes up to Deichkind and is in alphabetical order - I do have far more playlists than that.

There's also the Flow playlist, which I think can safely be ignored - it's just some kind of daily suggestion.

**Comment by vincelwt** [comment]
Oops, I never actually tested with more than 20 playlists but should be a simple API's pagination issue and an easy fix. Should be fixed in next release!

**Comment by vincelwt** [comment]
Fixed ;) Will be available with next release
