### ISSUE TITLE
Spotify playback uses Youtube instead of Spotify

### ISSUE THREAD

**Issue by fhaglund** [vincelwt/harmony#203]
Exactly the same behavior as seen in https://github.com/vincelwt/harmony/issues/201 – but with Spotify.

**Comment by fiso** [comment]
Eh. This was me submitting, signed into the wrong account.

**Comment by vincelwt** [comment]
This is the normal behavior of Harmony.
I don't know of any way to change this for Spotify at the moment. 
To play tracks directly from Spotify, librespot is still very much in beta and hard to implement, and there is no official way to do so.

**Comment by holms** [comment]
There's absolutely no way to stream from Spotify, API doesn't provide such functionality. This hybrid approach is actually quite creative solution :grinning: The only annoying thing is that sometimes it plays tracks that has absolutely different name, so I can't even imagine how can something be picked from search which has 0% of similarity with spotify track name :)

**Comment by vincelwt** [comment]
Hey @holms, that may happen if the track is not on YouTube or not the first result of the the query, as Harmony does a simple search and plays the first result.

**Comment by holms** [comment]
@vincelwt any plans to handle this somehow? If it's not there - skip a song :)?

**Comment by vincelwt** [comment]
@holms I guess it could be done by checking the names' similarities, although this isn't 100% precise

**Comment by holms** [comment]
There are plenty of packages which can do this :) https://glench.github.io/fuzzyset.js/

**Comment by vincelwt** [comment]
@holms or via a simple Levenshtein distance function ;)
