### ISSUE TITLE
Cross Fading | Feature Request

### ISSUE THREAD

**Issue by ghost** [vincelwt/harmony#205]
Spotify has a cross fading feature in their desktop app and in their mobile app, I thought it would be nice to see this in Harmony as well. Is this possible?

**Comment by vincelwt** [comment]
Thanks for submitting. This feature is already on the Trello features request list board so I'll close this one.
It could be done using a plugin or maybe directly inside the Harmony's core, I'm still not sure.

**Comment by ghost** [comment]
Uhm...still waiting.
