### ISSUE TITLE
[Bug] Version 1.7.8 available for download?

### ISSUE THREAD

**Issue by DLMousey** [vincelwt/harmony#216]
Rather interesting bug on startup, Latest version (at time of writing) is 0.9 but the app reports that 1.7.8 is available for download.

![image](https://user-images.githubusercontent.com/8281699/38735517-df173d32-3f20-11e8-898a-4b4b369d0689.png)

When i dismiss the alert and attempt to refresh my libraries it displays the usual animated icon and tooltip but never finishes (started it going one morning and forgot it about it, Checked it the next day was still going!), Nothing seems to be logged to the console and network connection was fine the whole time.

Issue seems to persist after clearing settings/caches/clean installs etc.

OS: Windows 10 Pro (Build 16299.371) x64

**Comment by vincelwt** [comment]
Oops yes it was a bug server-side 😅
Could you confirm this is fixed (no more alerts) when running latest version? (0.9.1)

**Comment by DLMousey** [comment]
No longer seeing the 1.7.8 update available notice, However Harmony does still seem a bit unhappy, This is after a full settings reset, Re-enabled soundcloud only after restarting the application but there's still Spotify and Reddit shown in the list.

Screenshot with console open and errors expanded;
![image](https://user-images.githubusercontent.com/8281699/38867843-1f954d08-423d-11e8-8897-030845cf47b9.png)

**Comment by DLMousey** [comment]
Quick follow up on this issue, Went for a full uninstall & reinstall that seems to have got it,
Probably a touch extreme but i'm guessing something fell over in Harmony's file structure following an update 

![image](https://user-images.githubusercontent.com/8281699/38868913-bd4fdf38-4240-11e8-9e93-bd1fd45e7a3f.png)

**Comment by vincelwt** [comment]
Good. That's indeed what must've happened, although I thought I did the necessary so it wouldn't break on upgrades. I'll look more into it so it doesn't happen in the future. Thanks for reporting!

**Comment by DLMousey** [comment]
No problem, Since everything's back up and running i'll close this
