### ISSUE TITLE
Allow Soundcloud Go music?

### ISSUE THREAD

**Issue by ghost** [vincelwt/harmony#217]
Soundcloud Go music normally allows free users to listen to premium tracks for 30 seconds.
On Harmony, premium tracks do not show ;-;

Will it be possible to get premiums tracks to show on Harmony?

**Comment by ghost** [comment]
oh and also Soundcloud Playlists that I've 'liked' do not show as well

**Comment by vincelwt** [comment]
Hi!
Unfortunately, this is up to the artist to decide if the premium songs should be available via the API, see [this articled](https://soundcloudcommunity.com/share-embed-230064/soundcloud-go-api-access-6969068).

As for liked playlists, this can probably be done via the API ;) I added it to the 'will be made' section of the [features request board](https://trello.com/b/aO4L9OyM/harmony-features-requests).
