### ISSUE TITLE
YouTube song versions continue to be default even after YouTube plugin should be disabled.

### ISSUE THREAD

**Issue by globetrotterdk** [vincelwt/harmony#219]
YouTube song versions appear to continue to be default even after YouTube plugin should be disabled. I am using the 64-bit AppImage (harmony-0.9.1-x64.AppImage) on a Slackware64 14.2 install.

**Comment by vincelwt** [comment]
Hi! What do you means by continue to be default?

**Comment by globetrotterdk** [comment]
Well, for example: When I play Good-bye To Carolina by Lyle Lovett, with YouTube enabled, a NPR Tiny Desk concert video is played, rather than the song that (by itself) on Spotify. Even after having disabled the YouTube plugin, I still get the  NPR Tiny Desk concert video, instead of the song on Spotify.

I just wanted to add that I think that you have a great program (despite it being Electron based). Particularly important is the SoundCloud support. It makes it a lot easier to hear songs like this:
https://soundcloud.com/momentarygems/upstream
as the SoundCloud controls on the website aren't very good at all.

**Comment by vincelwt** [comment]
Yes this is the normal behavior of Harmony (https://getharmony.xyz/faq), as there isn't any possible way for Harmony to play the tracks directly from Spotify so we have to use YouTube.
If you'd like to disable the video to keep the audio only, you can do so by enabling the 'less, power hungry playing mechanism' option in YouTube's plugin options.
