### ISSUE TITLE
[enhancement] Add Yandex.Music support

### ISSUE THREAD

**Issue by MurzNN** [vincelwt/harmony#221]
[Yandex.Music](http://music.yandex.ru/) is very popular service in Russia, but native apps are too bad, and miss Linux support. So will be good to see support of Yandex.Music in Harmony player.

**Comment by vincelwt** [comment]
Hi!
If a developer wants to try and implement it, I'll provide help. 
But for now my focus is on making the app as usable and stable as possible, so I won't add any more services at the moment.
