### ISSUE TITLE
Spotify not playing from Spotify? 

### ISSUE THREAD

**Issue by ghost** [vincelwt/harmony#224]
![image](https://user-images.githubusercontent.com/26362558/41488357-09d36b0c-70ba-11e8-89e3-cd12009891d3.png)

Not sure what's going on here. It seems that this entire time that Spotify in Harmony has been playing from YouTube. So I played the song "Toys", instead of Harmony playing the actually song, I am getting a kid's video about toys.

**Comment by vincelwt** [comment]
Yes, this is how Harmony works with Spotify and Deezer at the moment, as this is the only way to play tracks for these services. As explained https://getharmony.xyz/faq 
It tries to find the closest match on Youtube but it doesn't have a 100% success rate. 
This won't be fixed as long as Spotify doesn't release an usable sdk.

**Comment by ghost** [comment]
Alright thx! I just want to keep using Harmony, since Spotify likes to be buggy a lot. ugh, bugs in the official app, that doesn't look good for them lol.
