### ISSUE TITLE
Switching playlists doesn't work on compact mode

### ISSUE THREAD

**Issue by helderbarboza** [vincelwt/harmony#226]
Congratulations for the app, I'm using it everyday, also recommended to 2 friends.

![captura de tela de 2018-07-20 08-43-22](https://user-images.githubusercontent.com/29435727/43003068-109cc460-8bf9-11e8-851e-ac6f97f473ba.png)

When the window is resized to compact and switching playlist dropdown menu shows up, it is able to change the playlist, but it doesn't auto start playing songs from the picked playlist.

**Comment by vincelwt** [comment]
Hey!
This isn't a bug but a feature :) 
When you switch playlist, you don't necessarily want it to auto start playing.
The sidebar menu only plays the first playlist track when you **double click** a playlist. 
With a simple click it will also only change the playlist.
Dropdowns don't allow a way to differentiate simple and double clicks so it couldn't really be done with compact mode

**Comment by helderbarboza** [comment]
So it is not possible to play a different playlist while using compact mode?

**Comment by vincelwt** [comment]
I don't understand - yes it is possible to play a different playlist while using compact mode. 
from your message "**it is able to change the playlist, but it doesn't auto start playing songs from the picked playlist.**" -> there is the limitation. You can still switch playlists and manually start playing them tho.
Why would it not be possible to play a different playlist while in compact mode ?
