### ISSUE TITLE
Add mpd as a music source 

### ISSUE THREAD

**Issue by wtfaremyinitials** [vincelwt/harmony#24]
I think this app could be used as a nice mpd client. Thoughts?

**Comment by vincelwt** [comment]
Sure!
Before integrating new services, I would like to first make the plug-in system which will allow other devs to integrate other music sources.

**Comment by wtfaremyinitials** [comment]
A plug-in system sounds perfect! Tag me in something when you get that working. I'll make the mpd pugin

**Comment by vincelwt** [comment]
Great, closing until news.

**Comment by wtfaremyinitials** [comment]
:+1:
