### ISSUE TITLE
No devices mode

### ISSUE THREAD

**Issue by tracure1337** [vincelwt/harmony#241]
Really nice app but pretty useless (for me at least) without an option to select the output device (sonos for example).

My apology if this sounds rude, I don't mean it that way :-)

Possible inspiration from https://github.com/mrmekon/connectr and Spotify connect.

**Comment by vincelwt** [comment]
Thanks for the feedback!
Most OSs handle the output device and I don't think it should be part of Harmony's core as I prefer to keep it minimal. Maybe it could be part of a plugin.
