### ISSUE TITLE
Soundcloud playlists

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#26]
They aren't refreshing to display songs that I've liked and added to playlists on Soundcloud.

**Comment by vincelwt** [comment]
Did you liked the songs from Harmony ? 
Are the playlists refreshing when restarting the app ?

The refresh delay 1h - this means every hour the data will be updated

**Comment by NickFlamel** [comment]
I favorited a song on Soundcloud, and added it to a Soundcloud playlist last night. The song still hasn't shown up in Harmony.

**Comment by vincelwt** [comment]
Did you liked the song from Harmony or from another client ?

**Comment by NickFlamel** [comment]
I liked the song from the Soundcloud website

**Comment by vincelwt** [comment]
Could you try liking a song from Harmony, close the app and see if it still here when you re-open it ?

**Comment by NickFlamel** [comment]
I unliked a song and it disappeared when I relaunched Harmony.

**Comment by vincelwt** [comment]
Is this bug still present with 0.3.1 ?

**Comment by vincelwt** [comment]
Closing this for lack of answer with latest versions
