### ISSUE TITLE
Disable Notifications.

### ISSUE THREAD

**Issue by joshuapinter** [vincelwt/harmony#31]
Can't seem to find out where to disable notifications when a song changes. 

Running on Mac OS X. 

Additionally, going to the Notifications section of the System Settings doesn't show Harmony on the list of applications that are permitted to send notifications so I can't disable it there.

**Comment by vincelwt** [comment]
Hi @joshuapinter ,

There was an option like that, I removed it when I redesigned the settings page.
But it can be useful, will add it!

**Comment by joshuapinter** [comment]
👍

**Comment by vincelwt** [comment]
Available in latest release:
https://github.com/vincelwt/harmony/releases/latest
