### ISSUE TITLE
Spotify Covers

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#35]
Sometimes the spotify tab gets covers of songs instead of the actual song. A bit weird. (Noticed it on Takin' it Back by Dutty Moonshine if you want to test.)

**Comment by NickFlamel** [comment]
Okay, I listened to the whole thing, and it sounds like Harmony is pulling audio from a video that has Takin' it Back in the background.

**Comment by vincelwt** [comment]
Yes, unfortunately I can't fix this.
Because Spotify Web API doesn't have an ability to stream songs but only to get metadata, I had to use YouTube to get the audio of the songs.
It works great with most tracks, but some less-known tracks have problems.
