### ISSUE TITLE
Facebook oauth cookies are not enabled

### ISSUE THREAD

**Issue by redpop1** [vincelwt/harmony#36]
Hi,
I have a spotify account a long time on linux connected with facebook.

Login in on your application doesn't work because cookies are not enabled.

Facebook will not grant the login session for spotify due to cookies

**Comment by vincelwt** [comment]
Several users reported this bug, it's on my priority list
However I can't reproduce it :/
What main browser are you using ? Are logged on facebook on this browser ?

**Comment by redpop1** [comment]
I've tried it with firefox and chrome and both logged in in the two browsers.

**Comment by redpop1** [comment]
In your application which browser do you use? Is it the standard browser that comes with ubuntu?
I mean the package 'webbrowser-app'? Because several problems are reported with that package in UBUNTU 16.04.

Just for your information

**Comment by vincelwt** [comment]
@redpop1 No, it's a Chromium-based browser (Electron) 

It seems related to [this issue](https://github.com/electron/electron/issues/3360).

What I don't get is why sometimes it works and sometimes not.

**Comment by vincelwt** [comment]
Could you try with this build ?
https://dl.dropboxusercontent.com/u/39260904/harmony-0.2.3.deb

**Comment by redpop1** [comment]
Fixed, thanks...

**Comment by vincelwt** [comment]
Awesome, thanks for testing
