### ISSUE TITLE
Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by redpop1** [vincelwt/harmony#37]
Linux Ubuntu 16.04

Search function does not work.....

With local files, spotify, the search function does not work

**Comment by vincelwt** [comment]
Hi, could you try with the new release ?
https://github.com/vincelwt/harmony/releases/download/0.2.3/harmony-0.2.3.deb

**Comment by redpop1** [comment]
I found the problem.

I have my music files on a nfs  share. (network file system, also linux).
That's the reason it doesn't work.

If I copy some files to my local disk it works.

Do you think you can find the error why it doesn't work on nfs?

Thanks

Love your work.

**Comment by redpop1** [comment]
Sorry, again my mistake.

Nfs share works without a problem.
But I have my music on an nfs share with dropbox......
It seems that dropbox watching the folder is the problem or a combination of nfs and dropbox....

**Comment by redpop1** [comment]
Sorry, again my mistake.

Seems I hole different type of bug. Has nothing to do with nfs or dropbox, both are working.

It just has something to do with a large number of files.......then searching doesn't work anymore.

**Comment by vincelwt** [comment]
Approximately how much mp3s do you have ?

Can you type on the search box and sense a little lag or when you're typing nothing at all happens ?

**Comment by redpop1** [comment]
449 files, tested on a local drive without dropbox.... if i copy 10 files to another directory  with the same song I'm searching for it's working.

**Comment by redpop1** [comment]
![harmony-files](https://cloud.githubusercontent.com/assets/647670/18411579/6e53eb96-777a-11e6-808c-da47b0a7b9c5.png)

**Comment by vincelwt** [comment]
Would be great if you could run Harmony from the terminal like that:
`Harmony --enable-logging`

Then replicate the bug and send me what's showing on the terminal

**Comment by redpop1** [comment]
this seems repeating with every letter I type in the box

`[11240:0910/173854:INFO:CONSOLE(270)] "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined", source: file:///opt/Harmony/resources/app/app/js/main.js (270)
`

**Comment by vincelwt** [comment]
Thanks for reporting! I'll try to make a build soon
