### ISSUE TITLE
OGG and FLAC support

### ISSUE THREAD

**Issue by eridanired** [vincelwt/harmony#38]
Currently only the MP3 files in my library are recognized.

Would be great if other popular formats were to be playable too.

**Comment by vincelwt** [comment]
Ogg support is coming ;)

For now I can't integrate lossless formats as the default JS audio player only support MP3/wav/ogg but I may switch to Aurora.js or libgroove in the future, which support lossless formats.

Closing until further news

**Comment by vincelwt** [comment]
Reopening since electron may soon support Flac audio

**Comment by vincelwt** [comment]
Flac audio will be available with 0.5 .
