### ISSUE TITLE
Infinite login loop

### ISSUE THREAD

**Issue by freaktechnik** [vincelwt/harmony#4]
After entering credentials for google play music and then realizing that I have to generate an app password, because harmony doesn't use OAuth I am now stuck with an ever re-opening settings window. The only way to close harmony is to close the main window and then close the settings window (which throws an error, btw).

After changing the google password it never actually saved the new one and always reset to the old one (I could tell by the length). I then reset the cache and settings, which then lead to the Google Play Music login not even showing an error message below it anymore. Everything else still works.

**Comment by vincelwt** [comment]
Hello,

Did you installed Harmony via apt-get or you use the git repo directly?

Vincent.

Le lun. 6 juin 2016 23:32, Martin Giger <notifications@github.com> a écrit :

> After entering credentials for google play music and then realizing that I
> have to generate an app password, because harmony doesn't use OAuth I am
> now stuck with an ever re-opening settings window. The only way to close
> harmony is to close the main window and then close the settings window
> (which throws an error, btw).
>
> After changing the google password it never actually saved the new one and
> always reset to the old one (I could tell by the length). I then reset the
> cache and settings, which then lead to the Google Play Music login not even
> showing an error message below it anymore. Everything else still works.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vincelwt/harmony/issues/4>, or mute the thread
> <https://github.com/notifications/unsubscribe/AE20cpJL8QLTDeM3Za1qvQ0mtIVSzsPtks5qJJICgaJpZM4IvVrP>
> .
>
-- 

*--*

*Vincent L.*

**Comment by freaktechnik** [comment]
I installed it via the instructions on the github page.

**Comment by vincelwt** [comment]
Ok.

Can you check you have the latest version using "git pull" (I fixed
settings related bugs in recent commits) , then try to reset the settings
in the settings window?

Also it may seems obvious, but remember to click the save button in the
settings (I sometimes forgot it myself).

Le mar. 7 juin 2016 12:01, Martin Giger <notifications@github.com> a écrit :

> I installed it via the instructions on the github page.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/vincelwt/harmony/issues/4#issuecomment-224235392>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE20ckmBFZ-jCh2NZ1dZIHoMcMUj3NKKks5qJUFogaJpZM4IvVrP>
> .
>
-- 

*--*

*Vincent L.*

**Comment by freaktechnik** [comment]
By HitHub page I meant the [GitHub pages page](http://vincelwt.github.io/harmony/)

**Comment by vincelwt** [comment]
I fixed a lot of bugs since this version, but still haven't updated the apt-get repo.

Could you try installing the latest version ?
With following commands:

sudo apt-get autoremove harmony
wget https://dl.dropboxusercontent.com/u/39260904/harmony/64/harmony_0.2.2_amd64.deb
sudo dpkg -i harmony_0.2.2_amd64.deb

Then reset cache and settings.

**Comment by freaktechnik** [comment]
With that build everything worked - assuming the devtools are supposed to always show up in the settings ;) The <samp>Save</samp> button is really helpful :)

**Comment by vincelwt** [comment]
Oops, forgotten to re-comment the devtools opening, new build will correct.

Le mar. 7 juin 2016 à 22:54, Martin Giger <notifications@github.com> a
écrit :

> Closed #4 <https://github.com/vincelwt/harmony/issues/4>.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/vincelwt/harmony/issues/4#event-684956410>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AE20cm_Mte2p_mITSS7X9sQf9BavqQj0ks5qJdpsgaJpZM4IvVrP>
> .
>
-- 

*--*

*Vincent L.*

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,
Vincent L. vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/QEVgD4/iap/?hg=OIe2b7YEDz pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=7c2c3e31&email=reply@reply.github.com.&hg=OIe2b7YEDz
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,
Vincent L. vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/QEVgD4/c0f/?hg=yNZRrPTCtp pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=6fc29822&email=reply@reply.github.com.&hg=yNZRrPTCtp
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,
Vincent L. vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/QEVgD4/l7k/?hg=jAtxUcofqJ pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e1fef3c1&email=reply@reply.github.com.&hg=jAtxUcofqJ
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by freaktechnik** [comment]
uhm, you got a thing there.

**Comment by vincelwt** [comment]
@freaktechnik Sorry about that, email got hacked.

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,


Vincent L. vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/QEVgD4/c0f/?hg=oCrW1OwHet pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=6fc29822&email=reply@reply.github.com.&hg=oCrW1OwHet
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,


Vincent L. vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/QEVgD4/iap/?hg=jm3qUT2cln pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=7c2c3e31&email=reply@reply.github.com.&hg=jm3qUT2cln
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by vincelwt** [comment]
Bonjour vincelwt/harmony,


Vincent L. vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/QEVgD4/l7k/?hg=PlUTi2zqNY pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=e1fef3c1&email=reply@reply.github.com.&hg=PlUTi2zqNY
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
