### ISSUE TITLE
Feature Request: Auto Update.

### ISSUE THREAD

**Issue by joshuapinter** [vincelwt/harmony#41]
Would be so nice to auto-update the application. Also doing a check on launch or once a day to see if there's a new version.

**Comment by vincelwt** [comment]
That would indeed be great. For now I don't have a lot of time to prioritize this quite big feature, but when the app reach a stable state then why not :)

Closing until news

**Comment by joshuapinter** [comment]
Awesome. Keen to see the progress and to help out.
