### ISSUE TITLE
Add UPNP support?

### ISSUE THREAD

**Issue by JamesHealdUK** [vincelwt/harmony#43]
Would be awesome to be able to stream my music collection from Plex! Right now Im just using a Samba mount, but itd be much more convenient to have UPNP inbuilt.

**Comment by vincelwt** [comment]
Sure!
Before integrating new services, I would like to first make the plug-in system which will allow other devs to integrate other music sources.

**Comment by vincelwt** [comment]
Third parties plugins can now be installed within Harmony (docs still under writing) so if someone want to integrate UPNP it is now possible. I won't integrate it as an official plugin tough as I don't think this would benefit to a lot of persons.
