### ISSUE TITLE
GPM thumbs up is not sorted

### ISSUE THREAD

**Issue by w0xel** [vincelwt/harmony#47]
The titles in the Google Play Music thumbs up are not sorted correctly. Adding `console.log(a.RatingTimestamp)` to the function gives "undefined" for every comparison, `console.log(b.RatingTimestamp - a.RatingTimestamp)` gives NaN.

**Comment by vincelwt** [comment]
Could you try adding `console.log(f.lastRatingChangeTimestamp);` just after line 218 (file app/js/fetch.js) and send me one of the result data ?

**Comment by w0xel** [comment]
Actually, i didn't see the whole picture last time. It gives about 150 lines, half of them undefined, the other half gives a correct Timestamp. That would probably explain why some of them appear sorted.

Two lines, one with correct Timestamp, one with undefined:

```
[23202:0912/214302:INFO:CONSOLE(219)] "1393320267098000", source: file:///home/sebastian/harmony/app/js/fetch.js (219)
[23202:0912/214302:INFO:CONSOLE(219)] "undefined", source: file:///home/sebastian/harmony/app/js/fetch.js (219)
```

**Comment by w0xel** [comment]
Oh and it's not random. the first ~70 lines have a correct timestamp, the last ~80 have none. It somehow stops suddendly to have timestamps.

**Comment by vincelwt** [comment]
Oops, I meant to add 
`console.log(f);` after line 218
So we can see the whole data of the tracks with no timestamps (they must have another property we can use)

**Comment by w0xel** [comment]
I actually had to use `Object.keys(f)`, because it doesn't seem to have a toString(). 
A proper line gives 

> "id,title,imageBaseUrl,artist,album,albumArtist,composer,genre,durationMillis,track,disc,year,playCount,rating,creationDate,lastPlayed,storeId,matchedId,type,albumMatchedId,artistMatchedId,artistImageBaseUrl,explicitType,origin,previewToken,previewInfo,lastRatingChangeTimestamp,audioMatchedId,rightsInfo,autogenArtistArt,price,artistImage,canMakeRadio" 

while a non working line gives

> "id,title,imageBaseUrl,artist,album,albumArtist,composer,genre,durationMillis,track,disc,year,playCount,rating,creationDate,lastPlayed,storeId,matchedId,type,albumMatchedId,artistMatchedId,artistImageBaseUrl,explicitType,origin,previewToken,previewInfo,audioMatchedId,rightsInfo,autogenArtistArt,price,artistImage,canMakeRadio"

**Comment by vincelwt** [comment]
Mm, there is no timestamp in the later ones.
Do you know how these tracks are differents ? Were the ones without timestamp liked a very long time ago ? Are some of them uploaded and others all-access ? 

I really can't see why they wouldn't have timestamps :/

**Comment by w0xel** [comment]
Yep seems like the older (added let's say 2 years ago) songs do not have a timestamp, which is strange.
But what is even more strange, and that was the original reason i posted this issue, and i noticed this just now, is that there are always some old songs on top (like shortly added) which shouldn't be there. I'm investigating right now if they have some special timestamp so they can be sorted out.

For the old songs: For me it isn't important that they are sorted. I don't remember in which order i added those year-old songs anyway, but the new songs should really be in the right order.

**Comment by w0xel** [comment]
I sent you a pull request. Was simply due to the fact that sort can't handle "NaN"
