### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Mosbysoomby** [vincelwt/harmony#50]
Uncaught Exception:
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: main.js:448:15.
    at BrowserWindow.callIntoRenderer (/opt/Harmony/resources/electron.asar/browser/rpc-server.js:189:19)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)

Elementary OS 0.4 Loki

**Comment by vincelwt** [comment]
Could you give more info on the issue ? Version you're using ? Are you using it from source code or from a deb package ? After what action did it happen ? Did you copy the error from the command line or from the Devtools ? What happened after that ?

**Comment by vincelwt** [comment]
Closing until precisions
