### ISSUE TITLE
Icon displaying in low quality, missing in some places

### ISSUE THREAD

**Issue by sachk** [vincelwt/harmony#51]
[Here's what i mean](http://imgur.com/a/I01dx)

**Comment by vincelwt** [comment]
Could you try with the zip version? (if you tried with the installer, or with the installer if you tried with the zip)

I can't access to a windows machine right now.

**Comment by sachk** [comment]
i've tried both.

**Comment by vincelwt** [comment]
It seems to be an issue with electron-builder, I'll create an issue on their project

**Comment by sachk** [comment]
Cool, tell me when its fixed

**Comment by vincelwt** [comment]
Could you try with latest release 0.3.2 ? There is a new icon with this release

**Comment by sachk** [comment]
This is a bit unrelated, but could you add support for tidal, the lossless
music streaming service?

**Comment by sachk** [comment]
It works, but the icon is missing in some places and its really low quality.
![untitled-1](https://cloud.githubusercontent.com/assets/10218019/19224383/7751c624-8ed0-11e6-9aeb-e9c264b23db9.jpg)

**Comment by vincelwt** [comment]
Ok, thanks for testing, I got some more testing to do.

As for tidal, I guess it could be done but for now my focus is on Deezer, and then Hypemachine before anything more. You can try and implement it if you want though.

**Comment by vincelwt** [comment]
@sachk It should've been solved in 0.4, could you confirm ?
