### ISSUE TITLE
OSX Close and other feedback

### ISSUE THREAD

**Issue by petravicius** [vincelwt/harmony#53]
Hey,

Sorry if this isn't the right place to leave this feedback, but didn't find any other way to get in touch with developer. 
Really like Harmony so far, one issue I found with it was that pressing close icon on OSX version it closes the app, which isn't intuitive and it's quite annoying. The Mac OS convention is that close icon shouldn't close the application, but hide it in the background and keep it running. Besides this it would be nice if you'd add check for updates feature, as there's currently no way inside the app to check if it's up to date.

Keep up the great work,
Cheers

**Comment by vincelwt** [comment]
Hi @petravicius,

Good place to post problems :)

Do you mean it completely closes the app or it "hibernate it" ? I think last time I checked on a Mac it kept it on background but did "reset" the app when I brought it back on the front. Could you confirm that ?

I know even like that, it doesn't behave good accordingly with OSX, but just to make sure until I make it react great.

As for updates, if a new release is available it should show a notification when you start the app ;)

**Comment by petravicius** [comment]
Yeah, that's what I meant. It doesn't close the app, but hibernates and music stops playing.

Oh, I didn't know about the update notification. Cool :)

**Comment by vincelwt** [comment]
Ok thanks, it should be pretty easy to fix.

**Comment by davorb** [comment]
Additionally, it would be nice if the app quit when you pressed ```Command-Q```, and if there was an option to quit in the menubar.

**Comment by vincelwt** [comment]
@davorb App should quit with Cmd+Q since 0.2.4, does it works with you ?

**Comment by vincelwt** [comment]
Ok I should have fixed this @petravicius, I still need to try on a Mac but it should be OK.
Will be available with future 0.3 release.

**Comment by davorb** [comment]
@vincelwt it's not working for me. is there a way to check what version I'm running? when I open up the console, it says that the latest version is 0.2.4 and it *doesn't* tell me to upgrade, so I assume that I'm running that version.

**Comment by vincelwt** [comment]
@davorb Then yes, you should be running 0.2.4. Do you see the menu bar with Copy/Paste/Developers tools and co ?

**Comment by davorb** [comment]
Yes, I do.

**Comment by vincelwt** [comment]
Can you confirm there is "Quit" item in this menu that quit the app when clicked ? This item is linked to the Cmd+Q shortcut that is supposed to quit the app

**Comment by davorb** [comment]
There is no *Quit* menu item.

**Comment by vincelwt** [comment]
@davorb Could you send a screenshot of the menu ?

**Comment by vincelwt** [comment]
@davorb Could you try with latest release ?

**Comment by petravicius** [comment]
Hey again,

I've just tried the latest v3 of the app and can confirm that close and Cmd+Q works perfectly on OSX now. Though I can also confirm that I never get any notifications to update, even if new version is available. Have to update manually, @davorb also seems to have been having issue in finding out which version he is using. 
So I still believe it would be really useful to be able to check what version you're currently using and see if there are any updates inside the app. 
Also I can't find how to change the player to dark version?

Besides this, everything seems great.
Thanks!

**Comment by vincelwt** [comment]
@petravicius Can you also confirm that music stays in background when you close the app but don't quit ?

For the notification and current version issue, I'll add a button to check if a new version is available.
However it should've popped up a notification when I released the 0.3.0 version, so there must be a problem.

You can toggle dark version by pressing Cmd+D . I may add a button in the settings.

@davorb Can you also confirm that Cmd+Q works ?

**Comment by petravicius** [comment]
@vincelwt Yeah, music stays playing in the background when you close the app.

Dark mode looks awesome and it would be good to include a button in the settings for it. 

Thanks for your great work!

**Comment by davorb** [comment]
I just upgraded, and the new version works great.

Thanks for spending the time on this!

**Comment by vincelwt** [comment]
Great! Closing this
