### ISSUE TITLE
Can't go to sleep quickly

### ISSUE THREAD

**Issue by HorlogeSkynet** [vincelwt/harmony#54]
Hello there !

I use to suspend my Linux while it's playing music in background.
Others softwares don't say anything and continue their job when the PC is waken up.
But here Harmony doesn't look happy:

![When trying to suspend Debian](https://puu.sh/reaCI/7a352a4028.png)

Is there a way to let Harmony getting interrupted ?

Thx !

**Comment by vincelwt** [comment]
What system are you using ? Ubuntu-based ?

With elementary OS (ubuntu-based) when I suspend, everything goes fine, so I can't reproduce :/

**Comment by HorlogeSkynet** [comment]
Hey, thanks for answering !

Yeah I wanted, but totally forgot, to mention that...
I'm running latest Debian Stretch (SiD), with Cinnamon.

But I had got others bugs like blank pages (also when Cover Flow was disabled), music playing stopping alone, ...

**Comment by vincelwt** [comment]
Okay, I'll give it a look see why it may be doing that 

I would be interested in knowing about your other bugs! 
Could you open other issues for the bugs with some details on how to reproduce? 

Thanks!

**Comment by HorlogeSkynet** [comment]
Yeah I can open one for the blank pages, for the other I didn't really know how and why it happened... See you on the other side
