### ISSUE TITLE
Notification icon not working in some linux configurations

### ISSUE THREAD

**Issue by w0xel** [vincelwt/harmony#55]
![notify_not_working](https://cloud.githubusercontent.com/assets/12088060/18615036/a225e560-7d9b-11e6-959c-730729546f6a.png)

Node-notifier just wrapping the 'notify-send' command on linux leads to certain incompatiblities (Screenshot from elementaryOS loki). 

I am already able to provide a fix: Electron native notifications had some shortcomings earlier, but fixed them in recent releases (now compatible with windows <=7 and >=8, better linux support, osx always worked). They also use native C++ libraries instead of wrapping the commands on all platforms.
I replaced electron 1.2.8 (that is in use currently) by electron 1.4.0 and replaced the notifier-send notification call with a Electron notification:  

![notify_working](https://cloud.githubusercontent.com/assets/12088060/18615067/a8f82118-7d9c-11e6-84e8-fde41fa0ed58.png)

I would gladly help and send you a pull request replacing all notification calls with Electron notifications, if you are willing to upgrade Electron. (Just test it. Harmony works great with Electron 1.3.4/1.4.0.
If you get a 'Module version mismatch. Expected x, got _y_.' Just do 
`npm rebuild --runtime=electron --target=1.3.4 --disturl=https://atom.io/download/atom-shell --abi=y`
where you replace 1.3.4 with the electron version you're using and y with the abi version it got. This happens when electron-prebuilt was built with a different version of node than your system uses)

**Comment by vincelwt** [comment]
Haha I was just looking at this issue too :) 

You can open a pull request, but maybe wait a few hours/days until I push my work for the plugin system, because I'm afraid there's gonna be a lot of merge conflicts (sometimes is a pain to solve).

Thanks!

**Comment by w0xel** [comment]
ok :)

**Comment by vincelwt** [comment]
Alright I pushed my work, feel free to send pull requests ;) 

I'll try now to make the code much cleaner for developers willing to participate, as it's still a lot messy

**Comment by vincelwt** [comment]
I updated Electron to latest 1.4.0
