### ISSUE TITLE
Blank page when running Harmony

### ISSUE THREAD

**Issue by HorlogeSkynet** [vincelwt/harmony#58]
Re-hello,

So that happened several times. When I ran Harmony, sometimes the window shows up with only a blank page, and there was nothing to do...
I've figured out that if you remove the Harmony directory in `~/.config`, the next time you'll launch Harmony, you should get something...

Problem with cached data ?

@+

EDIT: It's also on the Debian Stretch

**Comment by vincelwt** [comment]
Hi,

Could you try running Harmony from the command line:
`Harmony --enable-logging`

And send the command line output once the bug appeared ?

That would be a great help to identify the problem. Thanks!

**Comment by HorlogeSkynet** [comment]
I've just got one !

For you: https://puu.sh/rhGFE/a62d202232.png

See ya

**Comment by vincelwt** [comment]
weird, no bug is appearing on the command line. can you see at least the sidebar and the player on the top and the footer on the bottom (with the buttons) or none of that and just blank screen ?

**Comment by HorlogeSkynet** [comment]
That's pretty weird yeah !

No I just have nothing... Blank page, only the title of the window shows something (the last music that has been played)...

Cinnamon is wrecking everything ?
Plus: I never had a album preview in the widget of Cinnamon, is it normal ?

**Comment by vincelwt** [comment]
I just checked you screenshot again and noticed the screen doesn't include all the logs outputing at start.
Maybe you didn't took the error part ? Sometimes this is marked as 'info' even if it is an error.

In doubt could you resend me the whole output of the command line ? Maybe in case you missed something.
That could be the only way for me to find the bug :/

Thanks!

**Comment by HorlogeSkynet** [comment]
Hey,

Yeah I didn't capture the logs above because there was just some information on tracks played...
I had parsed all the lines, there was nothing bad... until this latest warning. Bank window happened at this time...

Thx

**Comment by vincelwt** [comment]
Hi could you try with the latest release ?
https://github.com/vincelwt/harmony/releases/latest

**Comment by HorlogeSkynet** [comment]
Hello !

Thanks for the new release. I've updated and this is why I got in less than 45 seconds after starting it:

https://puu.sh/ryIa6/61d2fe5c68.png

I'm still on the second shot for some hours without any trouble...
I'll keep using Harmony for the some days to come. If this bug does not come back, we'd be able to close this ;)

Bye !

**Comment by HorlogeSkynet** [comment]
Well well well... Here I am (sooner than expected) !

There is the last log I got before the white thing:

https://puu.sh/rz4Ku/4e4bd57bca.png

@+

**Comment by vincelwt** [comment]
What a weird bug :/
Are you able to predict when it is gonna happen ? After what actions ?

**Comment by HorlogeSkynet** [comment]
It happens whenever it wants... I can't give you any clue for that...

**Comment by michote** [comment]
I experience a similar bug. I can't get Harmony (Ver 0.4.1) to play anything (local content). For some time I see the loading badge an then the hole window turns white.
My output after deleting the Harmony directory in ~/.config is: <script src="https://gist.github.com/anonymous/ebedd20e6363466e670461bdc1296881.js"></script>
