### ISSUE TITLE
Google Play Music Playlists - Show ablum and number 

### ISSUE THREAD

**Issue by jwhipp** [vincelwt/harmony#59]
Harmony currently doesn't show the playlist or album which makes sorting music really difficult.  At the very least, the number from the playlist should be the default sorting.   It's also missing the album field which would also be nice to have so you can go to the album directly and play it.

**Comment by vincelwt** [comment]
Hi!

Not sure about what you mean, Harmony shows the album column if the window is large enough. You can right click on a track and select "View album". Also the songs are by default sorted by artist, then album, then album number.

![screenshot from 2016-09-20 07 30 45](https://cloud.githubusercontent.com/assets/5092466/18658536/3d39a14a-7f04-11e6-860b-612d1b6905e4.png)

Could you be a bit more precise ? Thanks :) !
