### ISSUE TITLE
Problem with .zip on Mac Os 10.11.6 with The Unarchiver

### ISSUE THREAD

**Issue by clambelet** [vincelwt/harmony#62]
Hi,

For information (I don't know if it's a problem from Harmony or not). If I unzip the Harmony file with [The Unarchiver](http://unarchiver.c3.cx/unarchiver) (instead of the system utilies), the app can't be open, a modal state:

> Can not open the application "Harmony" because it may be damaged or incomplete.
(translated from french)

It does work with the system Utility archive.

**Comment by vincelwt** [comment]
Thanks for reporting, but I doubt it is a problem with Harmony !
