### ISSUE TITLE
More standards-compliant deb packaging

### ISSUE THREAD

**Issue by probonopd** [vincelwt/harmony#66]
The current deb package does not follow the usual debian conventions:
* Should install to `/usr` rather than `/opt`
* desktop file should be named `harmony.desktop` rather than `Harmony.desktop`
* Executable name should be `harmony` rather than `Harmony`
* deb file should be named `harmony_$VER_amd64.deb` rather than `harmony-$VER.deb`

**Comment by vincelwt** [comment]
Output files are directly from electron-builder, I don't have much control over that

**Comment by probonopd** [comment]
Didn't realize you are using electron-builder. Could you please turn on the AppImage target?

**Comment by vincelwt** [comment]
@probonopd It is turned on, will be available with next release in the following days :) (BTW, amazing work)

**Comment by vincelwt** [comment]
AppImage available with latest release 
https://github.com/vincelwt/harmony/releases/latest

**Comment by probonopd** [comment]
Thank you very much @vincelwt, it is working well for me on 64-bit Ubuntu.

**Comment by vincelwt** [comment]
Great, if you have a bug with update notification popping every time, I just fixed it and am currently deploying 0.3.1 to prevent that.
