### ISSUE TITLE
5-star rating system

### ISSUE THREAD

**Issue by marek287** [vincelwt/harmony#73]
Is this possible to implement 5 start rating system to Harmony google play music?
I found this Tampermonkey script:
https://github.com/Velenir/google-play-music-star-ratings/blob/master/GPMusic-stars-rating.jQuery.js

https://productforums.google.com/d/msg/play/HwKmVF5N5YA/elrxaUL_BgAJ

**Comment by vincelwt** [comment]
Hi,

I don't see why implement a 5 stars rating system ?

Google themselves don't use this system anymore (instead thumbs up / thumbs down) and it won't accord well with the way the app works with the like button.

**Comment by marek287** [comment]
If you have rated all your library 6000 songs with 2-5 stars rating and suddenly you have only thumbs up  and down then its seems that your hard work was useless. This Tampermonkey scipt makes it alive again.

**Comment by vincelwt** [comment]
I don't think this would be a great think to have in Harmony, as I don't think a lot of users use this feature and this would be against Harmony's current design.

Feel free to maybe fork the project!
