### ISSUE TITLE
Harmony dark mode

### ISSUE THREAD

**Issue by NickFlamel** [vincelwt/harmony#77]
[http://image.prntscr.com/image/0d0fdc15df3645989fe5c56b6b9fff51.png](http://image.prntscr.com/image/0d0fdc15df3645989fe5c56b6b9fff51.png)

Dark mode doesn't recolor the sidebar or the top bar.

**Comment by NickFlamel** [comment]
Also, on the release build, the icon in the top left is cut in half.

**Comment by vincelwt** [comment]
Oops, yeah that's due to window white theme, having more priority than dark mode, thanks for reporting, I'll fix that!
