### ISSUE TITLE
shortcut to queue songs

### ISSUE THREAD

**Issue by Alok** [vincelwt/harmony#78]
I find it infuriating that Spotify is built on the idea of a queue of songs, but there's no keyboard shortcut to do so. Can such a shortcut please be added to this app?

**Comment by brahiansoto** [comment]
That would be nice

**Comment by vincelwt** [comment]
Hi, 
What exactly would the shortcut do ? Like the "add to queue" in the contextual menu ?

**Comment by Alok** [comment]
If you have a song highlighted, it should be equivalent to hitting "play next" in the right click menu.

**Comment by vincelwt** [comment]
Will be available with next release.
