### ISSUE TITLE
Improve Google auth flow

### ISSUE THREAD

**Issue by nblackburn** [vincelwt/harmony#8]
All other services create popups to sign in through official channels but Google works differently meaning it misses out on TOTP support and creating the impression of it being a second class citizen.

**Comment by vincelwt** [comment]
Not sure if we can use an oauth based authentification as other services, as the API used for Google PM is unofficial.

Will look into it to see if it's possible

**Comment by aidanharris** [comment]
I found an old issue [here](https://github.com/jamon/playmusic/issues/26). It seems the best way to use the playmusic library with a 2-factor enabled Google account is to create an app specific password. 

Would it be possible to detect if an account has 2-factor enabled and provide a hint or perhaps open a webpage with instructions, so a user doesn't wonder "Why doesn't this work?" and give up on harmony.

**Comment by vincelwt** [comment]
Thanks @aidanharris, I will add it to the README

**Comment by dwaq** [comment]
I think the method listed in the README "enable the insecure app access" is not the best route to go. I suggest linking users to the [app password](https://security.google.com/settings/security/apppasswords) page, where they can create a specific password for the Harmony app.

I have tested and confirmed that this method works.

**Comment by vincelwt** [comment]
Added to the README :)

**Comment by vincelwt** [comment]
I close this, as I don't think there is anything more doable with this current API.
