### ISSUE TITLE
Media keys unresponsive

### ISSUE THREAD

**Issue by dispix** [vincelwt/harmony#83]
In some cases, the media keys on mac are not controlling the harmony player. This may happen after the computer comes out of sleep, I'm not certain it's related though. Keyboard controls (like `cmd+left` or `space`) work as intended when the harmony is in focus.

Informations:
- MacBook Pro 13" mid-2010
- OSX 10.11.6
- Harmony v0.3.2

**Comment by gr0wlithee** [comment]
Media keys are also unresponsive on my Windows 10 PC.

**Comment by vincelwt** [comment]
Should be ok now with 0.5.1 :)
