### ISSUE TITLE
Playing a random song on the playlist in shuffle as first song

### ISSUE THREAD

**Issue by kuzdogan** [vincelwt/harmony#86]
When playing a playlist, it would be better to play a random song instead of playing the first one. Currently when a playlist is double clicked the app plays the first song on the list

**Comment by vincelwt** [comment]
Sorry for the late answer.
Not sure why this is a problem? 
Also, making double clicking play the first track of the list even in shuffle mode is more clear to the user that double clicking plays the first track of the playlist.

**Comment by kuzdogan** [comment]
Hi
I totally forget what I've meant by this :) as yours makes sense. Maybe I wanted to have a random song played if I'm in shuffle mode, but I don't see a problem at all. 
Thanks for the response. I think we can close this.
