### ISSUE TITLE
A little BIG BUG

### ISSUE THREAD

**Issue by Despin** [vincelwt/harmony#87]
It is a bug that simply opens as two or three settings screens per second, and is unbearable

**Comment by vincelwt** [comment]
Hi, could you give more info? 
What system are you using, what version are you using, how to reproduce , the log available when you press ctrl-alt-i, etc..

**Comment by Seebz** [comment]
I got this issue after upgrading from `harmony-0.3.1-amd64.deb` to `harmony-0.3.2-amd64.deb` using Ubuntu package manager.

I have solved by disconnecting/reconnecting my soundcloud and spotify accounts.


Note: I updated from "0.3.2" to "0.4.0" by the same way and I dont got any problem.

**Comment by vincelwt** [comment]
@Despin could you try with latest versions and confirm the bug is gone ?

**Comment by Despin** [comment]
Finally I did not happen to me that bug since the last update, thanks !!!!
