### ISSUE TITLE
Soundcloud : Sign-in using Google

### ISSUE THREAD

**Issue by PierrickBrun** [vincelwt/harmony#89]
The Sign-in using google button doesn't work on my case :
On click : nothing happens
If I click on Cancel after trying to connect using Google I get two error messages : 'Error, please try again later !' and then 'access_denied'.

I've tested it using linux mint 18 and kubuntu 16.04 and had the same result

**Comment by vincelwt** [comment]
I can confirm, but I have no idea on how to correct it :/

**Comment by vikene** [comment]
I guess their api is the issue. They are still using some older version of Google Oauth.

**Comment by vincelwt** [comment]
This seems to be fixed now
