### ISSUE TITLE
More icons

### ISSUE THREAD

**Issue by Seebz** [vincelwt/harmony#91]
Please provide more icon sizes...

Latest version (0.4.0) only provides icon 256x256 while previous version (0.3.2) contains icons in size 32x32, 64x64, 128x128 and 256x256.

It would be good to also provide a 16x16 icon because it is used in some desktop "sound menu".

Note: I am using `amd64.deb` releases.

(please forgive my bad english)

**Comment by vincelwt** [comment]
Oups yes I just checked on my Ubuntu and there is a problem with the icon in the sound menu. I'll put them back.
