### ISSUE TITLE
Some songs play off pitch, or incorrect pitch

### ISSUE THREAD

**Issue by prediscover** [vincelwt/harmony#96]
For some songs that play on spotify For the song "all we got" by chance the Rapper, Harmony music player plays the song in an incorrect pitch. What's going on?

**Comment by NickFlamel** [comment]
Harmony pulls spotify songs from YouTube because Spotify's API doesn't allow you to play spotify songs from anything but the spotify client.

**Comment by prediscover** [comment]
Is it possible to choose which youtube version it plays? cause sometimes it plays a terrible version off of youtube.

**Comment by vincelwt** [comment]
Yes, sadly this is the only way to fetch Spotify and Deezer tracks for now. It plays the youtube video with the closer duration to the original track, among the top 5 Youtube results.
